#include "../src/music.hpp"
#define DR_MP3_IMPLEMENTATION
#include "../src/dr_mp3.h"
#include <cassert>
#include <cmath>
#include <fstream>
#include <iostream>
int main(){unsigned char latin[]={0,'B',0xe9};assert(day::musicTagText(latin,3)=="Bé");unsigned char utf16[]={1,255,254,0x2d,0x4e,0x87,0x65};assert(day::musicTagText(utf16,7)=="中文");std::vector<unsigned char> tag={'T','I','T','2',0,0,0,5,0,0,3,'T','e','s','t','T','P','E','1',0,0,0,3,0,0,3,'M','e'};auto meta=day::parseMusicTag(tag,3,0);assert(meta.title=="Test"&&meta.artist=="Me");tag.pop_back();assert(day::parseMusicTag(tag,3,0).artist.empty());using namespace day;assert(MusicStatus{}.repeat==1);assert(mp3Path("SONG.MP3"));assert(!mp3Path("x.mp3.txt"));assert(trackName("ux0:music/album/日本語.mp3")=="日本語");assert(adjacentTrack(0,-1,3)==2);assert(adjacentTrack(2,1,3)==0);assert(adjacentTrack(0,1,0)==-1);assert(musicTime(3661)=="61:01");assert((musicQueue({"x/a.mp3","y/b.mp3","x/c.mp3"},"x")==std::vector<int>{0,2}));assert(musicQueue({"x/a.mp3"},"y").empty());
 for(int channel=1;channel<=2;++channel){drmp3 m{};assert(drmp3_init_file(&m,("tests/fixtures/music-tone-"+std::to_string(channel)+".mp3").c_str(),nullptr));assert(m.channels==unsigned(channel));assert(m.sampleRate==unsigned(channel==1?44100:48000));auto frames=drmp3_get_pcm_frame_count(&m);assert(frames>m.sampleRate*1.9&&frames<m.sampleRate*2.2);short pcm[2048];uint64_t count=0;long long energy=0;while(auto n=drmp3_read_pcm_frames_s16(&m,1024,pcm)){assert(n<=1024);for(unsigned i=0;i<n*m.channels;++i)energy+=std::abs(pcm[i]);count+=n;}assert(count==frames);assert(energy>1000000);assert(drmp3_seek_to_pcm_frame(&m,m.sampleRate));assert(drmp3_read_pcm_frames_s16(&m,1024,pcm)==1024);assert(m.currentPCMFrame==m.sampleRate+1024);drmp3_uninit(&m);}
 MusicOrder queue(123);std::vector<std::string> library={"x/a.mp3","x/b.mp3","y/c.mp3","x/d.mp3"};queue.reset(library,"x",0,"x/a.mp3");assert(queue.next("x/a.mp3",1,true,0)=="x/b.mp3");assert(queue.next("x/d.mp3",1,true,0).empty());assert(queue.next("x/d.mp3",1,true,2)=="x/a.mp3");assert(queue.next("x/a.mp3",1,true,3)=="x/a.mp3");queue.reset(library,"x",1,"x/a.mp3");std::vector<std::string> seen={"x/a.mp3"};for(std::string next=queue.next(seen.back(),1,true,1);!next.empty();next=queue.next(seen.back(),1,true,1)){assert(std::find(seen.begin(),seen.end(),next)==seen.end());seen.push_back(next);}assert(seen.size()==3);assert(queue.next(seen[1],-1,false,1)==seen[0]);assert(queue.next(seen[0],1,false,1)==seen[1]);unsigned char invalid[128]{};drmp3 bad{};assert(!drmp3_init_memory(&bad,invalid,sizeof(invalid),nullptr));std::cout<<"MP3 mono/stereo streaming, duration, seek, EOF and invalid input passed\n";}
