#pragma once
#include "input.hpp"
#include <regex>
namespace day {
inline Json& addressData(){static Json data=[](){try{Json j;std::ifstream f("app0:assets/address-rules.json");f>>j;return j;}catch(...){return Json::object();}}();return data;}
inline Json& subdivisionData(){static Json data=[](){try{Json j;std::ifstream f("app0:assets/subdivision-names.json");f>>j;return j;}catch(...){return Json::object();}}();return data;}
inline const Json& addressRule(const std::string& cc){static const Json empty=Json::object();auto it=addressData().find(cc);return it==addressData().end()?empty:*it;}
inline std::vector<std::string> addressParts(const std::string& s){std::vector<std::string> out;size_t start=0;while(start<s.size()){auto end=s.find('~',start);out.push_back(s.substr(start,end==std::string::npos?end:end-start));if(end==std::string::npos)break;start=end+1;}return out;}
inline bool usesPostal(const std::string& cc){const auto& r=addressRule(cc);return r.value("fmt",std::string{}).find("%Z")!=std::string::npos||r.contains("zip");}
inline std::string regionLabel(const std::string& cc,int language){std::string type=addressRule(cc).value("state_name_type",std::string{"province"});if(cc=="UA")return language?"Oblast":"Область";if(cc=="RU"||cc=="GB")return language?"Region":"Регион";if(cc=="DE"||cc=="AT")return language?"Federal state":"Федеральная земля";if(cc=="CH")return language?"Canton":"Кантон";if(cc=="CA")return language?"Province / territory":"Провинция / территория";if(type=="state")return language?"State":"Штат";if(type=="prefecture")return language?"Prefecture":"Префектура";if(type=="county")return language?"County":"Графство";if(type=="department")return language?"Department":"Департамент";if(type=="emirate")return language?"Emirate":"Эмират";if(type=="parish")return language?"Parish":"Округ";if(type=="district")return language?"District":"Округ";if(type=="island")return language?"Island":"Остров";return language?"Province / region":"Провинция / регион";}
inline std::string postalLabel(const std::string& cc,int language){return cc=="US"?(language?"ZIP code":"ZIP-код"):(language?"Postal code":"Почтовый индекс");}
inline std::string regionName(const std::string& cc,const std::string& code,int language){if(code.empty())return {};auto key=searchFold(cc+code);auto it=subdivisionData().find(key);if(it!=subdivisionData().end())return it->value(language?"en":"ru",it->value("en",code));const auto& r=addressRule(cc);auto keys=addressParts(r.value("sub_keys",std::string{})),iso=addressParts(r.value("sub_isoids",std::string{})),names=addressParts(r.value("sub_lnames",r.value("sub_names",std::string{})));for(size_t i=0;i<keys.size();++i)if(keys[i]==code||(i<iso.size()&&iso[i]==code))return i<names.size()?names[i]:keys[i];return code;}
inline std::string resolveRegion(const std::string& cc,std::string value){value=trim(value);if(value.empty())return {};std::string code=upper(value);if(code.rfind(cc+"-",0)==0)code=code.substr(3);const auto& r=addressRule(cc);auto keys=addressParts(r.value("sub_keys",std::string{})),iso=addressParts(r.value("sub_isoids",std::string{})),names=addressParts(r.value("sub_names",std::string{})),latin=addressParts(r.value("sub_lnames",std::string{}));auto folded=searchFold(value);for(size_t i=0;i<keys.size();++i){auto candidate=i<iso.size()&&!iso[i].empty()?iso[i]:keys[i];if(code==upper(keys[i])||code==candidate||folded==searchFold(regionName(cc,candidate,0))||folded==searchFold(regionName(cc,candidate,1))||(i<names.size()&&folded==searchFold(names[i]))||(i<latin.size()&&folded==searchFold(latin[i])))return candidate;}for(auto it=subdivisionData().begin();it!=subdivisionData().end();++it)if(it.key().rfind(searchFold(cc),0)==0&&(folded==searchFold(it->value("ru",std::string{}))||folded==searchFold(it->value("en",std::string{}))||searchFold(cc+code)==it.key()))return upper(it.key().substr(2));return {};}
inline std::string normalizePostal(const std::string& cc,std::string value){value=upper(trim(value));if(cc=="US"&&value.size()==9&&value.find_first_not_of("0123456789")==std::string::npos)value.insert(5,"-");if(cc=="CA"){value.erase(std::remove(value.begin(),value.end(),' '),value.end());if(value.size()==6)value.insert(3," ");}if(cc=="JP"&&value.size()==7&&value.find_first_not_of("0123456789")==std::string::npos)value.insert(3,"-");return value;}
inline bool validPostal(const std::string& cc,const std::string& value){if(value.empty())return true;if(!usesPostal(cc)||value.size()>24||value.find_first_not_of("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 -")!=std::string::npos)return false;auto pattern=addressRule(cc).value("zip",std::string{});if(pattern.empty())return true;try{return std::regex_match(value,std::regex(pattern));}catch(const std::regex_error&){return true;}}
inline std::string postalExample(const std::string& cc){auto s=addressRule(cc).value("zipex",std::string{});return s.substr(0,s.find(','));}
}
