#pragma once
#include "json.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <map>
#include <string>
#include <vector>

namespace day {
using Json = nlohmann::json;
struct Date { int y=2026, m=1, d=1; };
inline bool leap(int y) { return y%4==0 && (y%100!=0 || y%400==0); }
inline int days(int y,int m) { static const int n[]={31,28,31,30,31,30,31,31,30,31,30,31}; return m>=1&&m<=12 ? n[m-1]+(m==2&&leap(y)) : 0; }
inline bool valid(Date a) { return a.y>=1900&&a.y<=2099&&a.d>=1&&a.d<=days(a.y,a.m); }
inline std::string key(Date a) { char s[40]; snprintf(s,sizeof(s),"%04d-%02d-%02d",a.y,a.m,a.d); return s; }
inline Date parseDate(const std::string& s) { Date a{0,0,0}; int end=0; if(sscanf(s.c_str(),"%d-%d-%d%n",&a.y,&a.m,&a.d,&end)!=3 || end!=(int)s.size() || !valid(a)) return {0,0,0}; return a; }
inline int weekday(Date a) { // Monday = 0; Gregorian calendar, independent of time zone.
    static int t[]={0,3,2,5,0,3,5,1,4,6,2,4}; int y=a.y-(a.m<3);
    return (y+y/4-y/100+y/400+t[a.m-1]+a.d+6)%7;
}
inline Date shift(Date a,int count) { while(count>0){if(++a.d>days(a.y,a.m)){a.d=1;if(++a.m>12){a.m=1;++a.y;}} --count;} while(count<0){if(--a.d<1){if(--a.m<1){a.m=12;--a.y;}a.d=days(a.y,a.m);} ++count;} return valid(a)?a:Date{1900,1,1}; }
inline Date month(Date a,int delta) { int index=a.y*12+a.m-1+delta; a.y=index/12; a.m=index%12+1; a.d=std::min(a.d,days(a.y,a.m)); return valid(a)?a:Date{delta<0?1900:2099,delta<0?1:12,1}; }
inline std::string trim(std::string s) { auto a=s.find_first_not_of(" \n\t\r"); if(a==std::string::npos)return {}; return s.substr(a,s.find_last_not_of(" \n\t\r")-a+1); }
inline std::string upper(std::string s) { for(char& c:s) if(c>='a'&&c<='z') c-=32; return s; }
inline bool countryValid(const std::string& s){return s.size()==2&&s[0]>='A'&&s[0]<='Z'&&s[1]>='A'&&s[1]<='Z';}
inline std::string clipUtf8(std::string s,size_t limit) { if(s.size()<=limit)return s; size_t p=limit; while(p>0&&((unsigned char)s[p]&0xc0)==0x80)--p; s.resize(p);return s; }
struct Mark { std::string title; int color=0; bool yearly=false; };
struct Location {
    bool valid=false, automatic=true; std::string city,country,region,zone; double lat=0,lon=0; int offset=0;std::string cityRu,cityEn;int geoname=0;std::string postal;
};
struct Holiday { std::string date,name,country,english; };
struct Weather { bool valid=false; double temperature=0,feels=0,wind=0; int code=0; std::string time; std::vector<double> highs,lows; std::vector<std::string> dates; Json details=Json::object(); };
struct Country { std::string code,name; int color=1; bool holidays=true,clock=false; std::string zone,clockCity; bool cityEnabled=true,cityPinned=false;double cityLat=0,cityLon=0; Country()=default;Country(std::string c,std::string n,int col=1,bool h=true,bool t=false,std::string z="",std::string city=""):code(std::move(c)),name(std::move(n)),color(col),holidays(h),clock(t),zone(std::move(z)),clockCity(std::move(city)){} };
struct WeatherPlace {Location location;Weather weather;long long updated=0;int origin=0;bool clock=true;};
struct HolidayCache { int year=0; std::string region; long long fetched=0; std::vector<Holiday> items; };
struct Appearance { int theme=0,style=0,background=0,bgColor=0,cardColor=0,opacity=90; std::string image; int bgRgb=-1,cardRgb=-1; };
struct State {
    int theme=0, style=0; long long revision=0; std::map<std::string,Mark> marks;
    Location location; Weather weather; std::vector<Holiday> holidays;
    int holidayYear=0; std::string holidayCountry,holidayRegion; long long updated=0;
    int language=0,units=0; bool time24=true,followLocal=true,international=true,keepScreen=true; int localColor=1,internationalColor=5,userColor=8,userRgb=0xe077bb;
    std::vector<int> recentColors;int themeMode=0; int textRgb=-1,accentRgb=-1; bool hints=false,dualUnits=false,autoAppearance=false; int dayStart=7,nightStart=20; Appearance dayLook,nightLook{1,0,0,0,0,90,""};
    std::string networkReport;std::vector<WeatherPlace> regions; std::vector<Country> countries,catalog; std::map<std::string,HolidayCache> caches;
};
inline Json encodeLocation(const Location& l){return {{"valid",l.valid},{"automatic",l.automatic},{"city",l.city},{"country",l.country},{"region",l.region},{"zone",l.zone},{"lat",l.lat},{"lon",l.lon},{"offset",l.offset},{"cityRu",l.cityRu},{"cityEn",l.cityEn},{"geoname",l.geoname},{"postal",l.postal}};}
inline Location decodeLocation(const Json& j) {
    Location l; l.valid=j.value("valid",false);l.automatic=j.value("automatic",true);l.city=j.value("city",std::string{});l.country=upper(j.value("country",std::string{}));l.region=upper(j.value("region",std::string{}));l.zone=j.value("zone",std::string{});l.lat=j.value("lat",0.0);l.lon=j.value("lon",0.0);l.offset=j.value("offset",0);l.cityRu=j.value("cityRu",std::string{});l.cityEn=j.value("cityEn",std::string{});l.geoname=j.value("geoname",0);l.postal=clipUtf8(j.value("postal",std::string{}),24);
    l.valid=l.valid&&countryValid(l.country)&&std::isfinite(l.lat)&&std::isfinite(l.lon)&&fabs(l.lat)<=90&&fabs(l.lon)<=180&&abs(l.offset)<=86400;return l;
}
inline void rememberColor(State& s,int rgb){if(rgb<0)return;s.recentColors.erase(std::remove(s.recentColors.begin(),s.recentColors.end(),rgb),s.recentColors.end());s.recentColors.insert(s.recentColors.begin(),rgb);if(s.recentColors.size()>12)s.recentColors.resize(12);}
inline int galleryBackground(int index){return index<=4?index:index+1;}
inline int backgroundGallery(int id){return id<=4?id:id==5?11:id-1;}
inline bool sameCity(const Location& a,const Location& b){if(a.country!=b.country)return false;if(a.geoname&&b.geoname)return a.geoname==b.geoname;if(a.lat==0&&a.lon==0&&b.lat==0&&b.lon==0)return a.city==b.city&&a.zone==b.zone;return a.valid&&b.valid&&std::abs(a.lat-b.lat)<.00001&&std::abs(a.lon-b.lon)<.00001;}
inline std::string locationKey(const Location& l){char coords[80];snprintf(coords,sizeof(coords),"|%.6f,%.6f",l.lat,l.lon);return l.city+"|"+l.country+"|"+l.zone+coords;}
// origin: 0 legacy, 1 primary city for country, 2 independent weather city, 3 additional country city.
inline std::string defaultZone(const std::string& code,const std::vector<std::string>& zones){std::string preferred=code=="UA"?"Europe/Kyiv":code=="RU"?"Europe/Moscow":"";return !preferred.empty()&&std::find(zones.begin(),zones.end(),preferred)!=zones.end()?preferred:zones.empty()?"":zones.front();}
inline void replaceCountryPlace(State& s,int index,const Location& l){if(index<0||index>=(int)s.countries.size())return;auto old=s.countries[index];auto key=locationKey(l);s.regions.erase(std::remove_if(s.regions.begin(),s.regions.end(),[&](const WeatherPlace& p){return p.origin<2&&p.location.country==old.code&&locationKey(p.location)!=key&&(p.origin==1||(p.location.zone==old.zone&&(old.clockCity.empty()||old.clockCity==p.location.city)));}),s.regions.end());s.countries[index].cityEnabled=true;s.countries[index].zone=l.zone;s.countries[index].clockCity=l.city;s.countries[index].cityPinned=true;s.countries[index].cityLat=l.lat;s.countries[index].cityLon=l.lon;auto found=std::find_if(s.regions.begin(),s.regions.end(),[&](const WeatherPlace& p){return sameCity(p.location,l);});if(found==s.regions.end()){if(s.regions.size()<16)s.regions.push_back({l,{},0,1});}else{if(found->origin!=2)found->origin=1;auto& c=s.countries[index];c.zone=found->location.zone;c.clockCity=found->location.city;c.cityLat=found->location.lat;c.cityLon=found->location.lon;}}
inline bool pruneLegacyDefaults(State& s,const Json& countryZones){size_t before=s.regions.size();s.regions.erase(std::remove_if(s.regions.begin(),s.regions.end(),[&](const WeatherPlace& p){if(p.origin!=0)return false;for(const auto& c:s.countries)if(c.code==p.location.country&&!c.clockCity.empty()&&countryZones.contains(c.code)&&!countryZones[c.code].empty()){std::string oldDefault=countryZones[c.code][0];if(p.location.zone==oldDefault&&c.zone!=oldDefault)return true;}return false;}),s.regions.end());return before!=s.regions.size();}
inline bool countryPlace(const Country& c,const Location& l){return c.cityEnabled&&l.country==c.code&&l.zone==c.zone&&(c.clockCity.empty()||l.city==c.clockCity)&&(!c.cityPinned||(std::abs(c.cityLat-l.lat)<.00001&&std::abs(c.cityLon-l.lon)<.00001));}
inline int trackedCityCount(const State& s){int total=s.regions.size();for(const auto& c:s.countries)if(c.cityEnabled&&!std::any_of(s.regions.begin(),s.regions.end(),[&](const WeatherPlace& p){return countryPlace(c,p.location);}))++total;return total;}
inline bool addCountryCity(State& s,int index,const Location& l){if(index<0||index>=(int)s.countries.size()||l.country!=s.countries[index].code)return false;auto& c=s.countries[index];if(!c.cityEnabled||c.clockCity.empty()){int projected=trackedCityCount(s);bool primaryExists=false,chosenExists=false;for(const auto& p:s.regions){primaryExists|=countryPlace(c,p.location);chosenExists|=sameCity(p.location,l);if(p.origin<2&&p.location.country==c.code&&locationKey(p.location)!=locationKey(l)&&(p.origin==1||(p.location.zone==c.zone&&(c.clockCity.empty()||c.clockCity==p.location.city))))--projected;}if(c.cityEnabled&&!primaryExists)--projected;if(!chosenExists)++projected;if(projected>16)return false;replaceCountryPlace(s,index,l);return true;}auto it=std::find_if(s.regions.begin(),s.regions.end(),[&](const WeatherPlace& p){return sameCity(p.location,l);});if(it!=s.regions.end()){if(!countryPlace(c,it->location))it->origin=3;return true;}if(trackedCityCount(s)>=16)return false;s.regions.push_back({l,{},0,3});return true;}
inline bool setCountryZone(State& s,int index,const std::string& zone){if(index<0||index>=(int)s.countries.size())return false;auto& c=s.countries[index];int projected=trackedCityCount(s);bool oldExists=false,newExists=false;for(const auto& p:s.regions){oldExists|=countryPlace(c,p.location);if(p.origin<2&&countryPlace(c,p.location))--projected;else if(p.location.country==c.code&&p.location.zone==zone)newExists=true;}if(c.cityEnabled&&!oldExists)--projected;if(!newExists)++projected;if(projected>16)return false;auto old=c;s.regions.erase(std::remove_if(s.regions.begin(),s.regions.end(),[&](const WeatherPlace& p){return p.origin<2&&countryPlace(old,p.location);}),s.regions.end());c.cityEnabled=true;c.zone=zone;c.clockCity.clear();c.cityPinned=false;return true;}
inline void removeCountryCity(State& s,int country,int place){if(country<0||country>=(int)s.countries.size()||place<0||place>=(int)s.regions.size())return;auto& c=s.countries[country];bool primary=countryPlace(c,s.regions[place].location);s.regions.erase(s.regions.begin()+place);if(primary){auto next=std::find_if(s.regions.begin(),s.regions.end(),[&](const WeatherPlace& p){return p.origin==3&&p.location.country==c.code;});if(next==s.regions.end()){c.cityEnabled=false;c.clock=false;c.clockCity.clear();c.zone.clear();c.cityPinned=false;}else{c.zone=next->location.zone;c.clockCity=next->location.city;c.cityPinned=true;c.cityLat=next->location.lat;c.cityLon=next->location.lon;next->origin=1;}}}
inline bool removeTrackedCity(State& s,int place){if(place<0||place>=(int)s.regions.size())return false;for(int i=0;i<(int)s.countries.size();++i)if(countryPlace(s.countries[i],s.regions[place].location)||(s.regions[place].origin==3&&s.countries[i].code==s.regions[place].location.country)){removeCountryCity(s,i,place);return true;}s.regions.erase(s.regions.begin()+place);return true;}
inline Json weatherJson(const Weather& w){return {{"valid",w.valid},{"temperature",w.temperature},{"feels",w.feels},{"wind",w.wind},{"code",w.code},{"time",w.time},{"highs",w.highs},{"lows",w.lows},{"dates",w.dates},{"details",w.details}};}
inline Weather weatherFromJson(const Json& w){Weather o;o.valid=w.value("valid",false);o.temperature=w.value("temperature",0.);o.feels=w.value("feels",0.);o.wind=w.value("wind",0.);o.code=w.value("code",0);o.time=w.value("time",std::string{});o.highs=w.value("highs",std::vector<double>{});o.lows=w.value("lows",std::vector<double>{});o.dates=w.value("dates",std::vector<std::string>{});o.details=w.value("details",Json::object());return o;}
inline Json encode(const State& s) {
    Json marks=Json::object(),holidays=Json::array(); for(const auto& p:s.marks) marks[p.first]={{"title",p.second.title},{"color",p.second.color},{"yearly",p.second.yearly}};
    for(const auto& h:s.holidays)holidays.push_back({{"date",h.date},{"name",h.name}});
    Json j={{"version",2},{"revision",s.revision},{"theme",s.theme},{"style",s.style},{"marks",marks},{"location",encodeLocation(s.location)},{"weather",{{"valid",s.weather.valid},{"temperature",s.weather.temperature},{"feels",s.weather.feels},{"wind",s.weather.wind},{"code",s.weather.code},{"time",s.weather.time},{"highs",s.weather.highs},{"lows",s.weather.lows},{"dates",s.weather.dates},{"details",s.weather.details}}},{"holidays",holidays},{"holidayYear",s.holidayYear},{"holidayCountry",s.holidayCountry},{"holidayRegion",s.holidayRegion},{"updated",s.updated}};
    j["preferences"]={{"language",s.language},{"units",s.units},{"time24",s.time24},{"followLocal",s.followLocal},{"international",s.international},{"localColor",s.localColor},{"internationalColor",s.internationalColor},{"userColor",s.userColor},{"userRgb",s.userRgb},{"keepScreen",s.keepScreen}};
    auto look=[](const Appearance& a){return Json{{"theme",a.theme},{"style",a.style},{"background",a.background},{"bgColor",a.bgColor},{"cardColor",a.cardColor},{"opacity",a.opacity},{"image",a.image},{"bgRgb",a.bgRgb},{"cardRgb",a.cardRgb}};};
    j["display"]={{"simple",true},{"recentColors",s.recentColors},{"themeMode",s.autoAppearance?2:s.themeMode},{"textRgb",s.textRgb},{"accentRgb",s.accentRgb},{"hints",s.hints},{"dualUnits",s.dualUnits},{"automatic",s.autoAppearance},{"dayStart",s.dayStart},{"nightStart",s.nightStart},{"day",look(s.dayLook)},{"night",look(s.nightLook)}};
    j["countries"]=Json::array();j["catalog"]=Json::array();j["caches"]=Json::object();
    for(const auto& c:s.countries)j["countries"].push_back({{"code",c.code},{"name",c.name},{"color",c.color},{"holidays",c.holidays},{"clock",c.clock},{"zone",c.zone},{"clockCity",c.clockCity},{"cityEnabled",c.cityEnabled},{"cityPinned",c.cityPinned},{"cityLat",c.cityLat},{"cityLon",c.cityLon}});
    for(const auto& c:s.catalog)j["catalog"].push_back({{"code",c.code},{"name",c.name}});
    for(const auto& c:s.caches){Json items=Json::array();for(const auto& h:c.second.items)items.push_back({{"date",h.date},{"name",h.name},{"english",h.english}});j["caches"][c.first]={{"year",c.second.year},{"region",c.second.region},{"fetched",c.second.fetched},{"items",items}};}
    j["networkReport"]=s.networkReport;j["regions"]=Json::array();for(const auto& place:s.regions)j["regions"].push_back({{"location",encodeLocation(place.location)},{"weather",weatherJson(place.weather)},{"updated",place.updated},{"origin",place.origin},{"clock",place.clock}});
    return j;
}
inline State decode(const Json& j) {
    int version=j.at("version");if(version!=1&&version!=2)throw std::runtime_error("Unknown save version");
    State s;s.revision=j.at("revision").get<long long>();s.theme=std::max(0,std::min(2,j.value("theme",0)));s.style=std::max(0,std::min(2,j.value("style",0)));
    for(auto p=j.at("marks").begin();p!=j.at("marks").end();++p) { if(s.marks.size()>=4096)break; if(!valid(parseDate(p.key())))continue; const auto& v=p.value(); s.marks[p.key()]={clipUtf8(v.value("title",std::string{}),240),std::max(0,std::min(6,v.value("color",0))),v.value("yearly",false)}; }
    s.location=decodeLocation(j.at("location")); const auto& w=j.at("weather");s.weather.valid=w.value("valid",false);s.weather.temperature=w.value("temperature",0.0);s.weather.feels=w.value("feels",0.0);s.weather.wind=w.value("wind",0.0);s.weather.code=w.value("code",0);s.weather.time=w.value("time",std::string{});s.weather.highs=w.value("highs",std::vector<double>{});s.weather.lows=w.value("lows",std::vector<double>{});s.weather.dates=w.value("dates",std::vector<std::string>{});s.weather.details=w.value("details",Json::object());
    for(const auto& h:j.at("holidays")){if(s.holidays.size()>=512)break; if(valid(parseDate(h.at("date"))))s.holidays.push_back({h.at("date"),h.at("name"),"",""});}
    s.holidayYear=j.value("holidayYear",0);s.holidayCountry=j.value("holidayCountry",std::string{});s.holidayRegion=j.value("holidayRegion",std::string{});s.updated=j.value("updated",0LL);
    if(version==2){const auto& pref=j.at("preferences");s.language=std::clamp(pref.value("language",0),0,1);s.units=std::clamp(pref.value("units",0),0,1);s.time24=pref.value("time24",true);s.followLocal=pref.value("followLocal",true);s.international=pref.value("international",true);s.keepScreen=pref.value("keepScreen",true);s.localColor=std::clamp(pref.value("localColor",1),1,10);s.internationalColor=std::clamp(pref.value("internationalColor",5),1,10);s.userColor=std::clamp(pref.value("userColor",8),1,10);s.userRgb=std::clamp(pref.value("userRgb",0xe077bb),-1,0xffffff);
        for(const auto& c:j.at("countries")){std::string code=c.at("code");if(countryValid(code)&&s.countries.size()<8)s.countries.push_back({code,c.value("name",code),std::clamp(c.value("color",1),1,10),c.value("holidays",true),c.value("clock",false),c.value("zone",std::string{}),clipUtf8(c.value("clockCity",std::string{}),80)});if(!s.countries.empty()&&s.countries.back().code==code){auto& saved=s.countries.back();saved.cityEnabled=c.value("cityEnabled",true);saved.cityPinned=c.value("cityPinned",false);saved.cityLat=c.value("cityLat",0.);saved.cityLon=c.value("cityLon",0.);saved.cityPinned=saved.cityPinned&&std::isfinite(saved.cityLat)&&std::isfinite(saved.cityLon)&&std::abs(saved.cityLat)<=90&&std::abs(saved.cityLon)<=180;}}
        for(const auto& c:j.at("catalog")){std::string code=c.at("code");if(countryValid(code)&&s.catalog.size()<300)s.catalog.push_back({code,c.value("name",code),1});}
        for(auto it=j.at("caches").begin();it!=j.at("caches").end()&&s.caches.size()<24;++it){if(!countryValid(it.key()))continue;const auto& v=it.value();HolidayCache cache;cache.year=v.at("year");cache.region=v.value("region",std::string{});cache.fetched=v.value("fetched",0LL);for(const auto& h:v.at("items")){if(cache.items.size()>=512)break;std::string date=h.at("date");if(valid(parseDate(date)))cache.items.push_back({date,h.at("name"),it.key(),h.value("english",std::string{})});}s.caches[it.key()]=cache;}
    } else if(countryValid(s.holidayCountry)&&s.holidayYear){HolidayCache c;c.year=s.holidayYear;c.region=s.holidayRegion;c.items=s.holidays;for(auto& h:c.items)h.country=s.holidayCountry;s.caches[s.holidayCountry]=c;}
    s.networkReport=clipUtf8(j.value("networkReport",std::string{}),24000);
    if(j.contains("regions"))for(const auto& place:j["regions"]){if(s.regions.size()>=16)break;Location l=decodeLocation(place.at("location"));if(l.valid)s.regions.push_back({l,weatherFromJson(place.at("weather")),place.value("updated",0LL),std::clamp(place.value("origin",0),0,3),place.value("clock",true)});}
    for(auto& c:s.countries)if(c.cityEnabled&&!c.cityPinned){auto found=std::find_if(s.regions.begin(),s.regions.end(),[&](const WeatherPlace& place){return place.origin==1&&countryPlace(c,place.location);});if(found==s.regions.end())found=std::find_if(s.regions.begin(),s.regions.end(),[&](const WeatherPlace& place){return countryPlace(c,place.location);});if(found!=s.regions.end()){c.cityPinned=true;c.cityLat=found->location.lat;c.cityLon=found->location.lon;}}
    if(j.contains("display")){const auto& v=j["display"];if(v.contains("recentColors"))for(const auto& c:v["recentColors"]){if(s.recentColors.size()>=12)break;int rgb=c.get<int>();if(rgb>=0&&rgb<=0xffffff&&std::find(s.recentColors.begin(),s.recentColors.end(),rgb)==s.recentColors.end())s.recentColors.push_back(rgb);}s.hints=v.value("hints",false);s.dualUnits=v.value("dualUnits",false);s.autoAppearance=v.value("automatic",false);s.themeMode=std::clamp(v.value("themeMode",s.autoAppearance?2:0),0,2);s.autoAppearance=s.themeMode==2;s.dayStart=std::clamp(v.value("dayStart",7),0,23);s.nightStart=std::clamp(v.value("nightStart",20),0,23);
        auto readLook=[](const Json& a){Appearance r;r.theme=std::clamp(a.value("theme",0),0,2);r.style=std::clamp(a.value("style",0),0,2);r.background=std::clamp(a.value("background",0),0,11);r.bgColor=std::clamp(a.value("bgColor",0),0,10);r.cardColor=std::clamp(a.value("cardColor",0),0,10);r.opacity=std::clamp(a.value("opacity",90),0,100);r.image=clipUtf8(a.value("image",std::string{}),240);r.bgRgb=std::clamp(a.value("bgRgb",-1),-1,0xffffff);r.cardRgb=std::clamp(a.value("cardRgb",-1),-1,0xffffff);return r;};s.dayLook=readLook(v.at("day"));s.nightLook=readLook(v.at("night"));s.textRgb=std::clamp(v.value("textRgb",-1),-1,0xffffff);s.accentRgb=std::clamp(v.value("accentRgb",-1),-1,0xffffff);if(!v.value("simple",false))s.style=s.dayLook.style;
    }else{s.dayLook.theme=s.theme;s.dayLook.style=s.style;}
    return s;
}
inline bool readState(const std::string& path,State& s) { try{std::ifstream f(path);if(!f)return false;f.seekg(0,std::ios::end);if(f.tellg()>8*1024*1024)return false;f.seekg(0);Json j;f>>j;s=decode(j);return true;}catch(...){return false;} }
inline State load(const std::string& dir) { State a,b;bool x=readState(dir+"/store0.json",a),y=readState(dir+"/store1.json",b);return x&&(!y||a.revision>=b.revision)?a:y?b:State{}; }
inline bool save(const std::string& dir,State& s) {
    // Alternate complete snapshots: interruption never overwrites the last good slot.
    State next=s; ++next.revision;std::string path=dir+"/store"+std::to_string(next.revision%2)+".json";
    try{std::string bytes=encode(next).dump();FILE* f=fopen(path.c_str(),"wb");if(!f)return false;bool ok=fwrite(bytes.data(),1,bytes.size(),f)==bytes.size();if(fflush(f)!=0)ok=false;if(fclose(f)!=0)ok=false;State check;if(!ok||!readState(path,check)||check.revision!=next.revision)return false;s.revision=next.revision;return true;}catch(...){return false;}
}
inline std::vector<std::pair<std::string,Mark>> marksFor(const State& s,Date date) {
    std::vector<std::pair<std::string,Mark>> out;std::string k=key(date);for(const auto& p:s.marks)if(p.first==k||(p.second.yearly&&p.first.substr(5)==k.substr(5)))out.push_back(p);return out;
}
inline std::string editKey(const State& s,Date date) { auto k=key(date);if(s.marks.count(k))return k;auto all=marksFor(s,date);return all.empty()?k:all.front().first; }
inline bool holidayCacheMatches(const State& s,int year){return s.holidayYear==year&&s.holidayCountry==s.location.country&&s.holidayRegion==s.location.region;}
inline std::vector<std::string> holidaysFor(const State& s,Date date) {std::vector<std::string> out;if(!holidayCacheMatches(s,date.y))return out;for(const auto& h:s.holidays)if(h.date==key(date))out.push_back(h.name);return out;}
inline std::vector<Holiday> parseHolidays(const Json& j,const Location& l,int year) {
    if(!j.is_array())throw std::runtime_error("Holiday response is not an array");std::vector<Holiday> out;
    for(const auto& h:j) { Date d=parseDate(h.at("date"));if(!valid(d)||d.y!=year)continue;bool match=h.value("global",false);if(!match&&!l.region.empty()&&h.contains("counties")&&h["counties"].is_array())for(const auto& c:h["counties"])if(c==l.country+"-"+l.region)match=true;if(match)out.push_back({key(d),h.value("localName",h.value("name",std::string("Праздник"))),l.country,h.value("name",std::string{})}); }
    return out;
}
inline Location parseIP(const Json& j) {if(!j.value("success",false))throw std::runtime_error("IP lookup failed");Location l;l.valid=true;l.city=j.at("city");l.country=j.at("country_code");l.region=j.value("region_code",std::string{});l.postal=j.value("postal",std::string{});l.lat=j.at("latitude");l.lon=j.at("longitude");l.zone=j.at("timezone").at("id");l.offset=j.at("timezone").at("offset");l=decodeLocation(encodeLocation(l));if(!l.valid)throw std::runtime_error("Invalid location");return l;}
inline Weather parseWeather(const Json& j) {Weather w;const auto& c=j.at("current");w.temperature=c.at("temperature_2m");w.feels=c.at("apparent_temperature");w.wind=c.at("wind_speed_10m");w.code=c.at("weather_code");w.time=c.at("time");const auto& d=j.at("daily");w.dates=d.at("time").get<std::vector<std::string>>();w.highs=d.at("temperature_2m_max").get<std::vector<double>>();w.lows=d.at("temperature_2m_min").get<std::vector<double>>();w.valid=std::isfinite(w.temperature)&&w.dates.size()==w.highs.size()&&w.dates.size()==w.lows.size()&&w.dates.size()<=10;if(!w.valid)throw std::runtime_error("Invalid weather");w.details=j;return w;}
inline std::vector<Country> activeCountries(const State& s){std::vector<Country> out;for(const auto& c:s.countries)if(c.holidays)out.push_back(c);if(s.followLocal&&s.location.valid){auto it=std::find_if(out.begin(),out.end(),[&](const Country& c){return c.code==s.location.country;});auto explicitCountry=std::find_if(s.countries.begin(),s.countries.end(),[&](const Country& c){return c.code==s.location.country;});if(it==out.end()&&explicitCountry==s.countries.end())out.insert(out.begin(),{s.location.country,s.location.country,s.localColor});}return out;}
inline int countryColor(const State& s,const std::string& code){if(code=="USR")return s.userColor;for(const auto& c:s.countries)if(c.code==code)return c.color;return code=="INT"?s.internationalColor:s.localColor;}
inline std::vector<Holiday> holidayItems(const State& s,Date date){std::vector<Holiday> out;for(const auto& c:activeCountries(s)){auto it=s.caches.find(c.code);std::string region=c.code==s.location.country?s.location.region:"";if(it==s.caches.end()||it->second.year!=date.y||it->second.region!=region)continue;for(const auto& h:it->second.items)if(h.date==key(date))out.push_back(h);}
    struct Day{int m,d;const char* ru;const char* en;};static const Day international[]={
        {1,24,"Международный день образования","International Day of Education"},{2,11,"Женщины и девочки в науке","Women and Girls in Science"},{3,8,"Международный женский день","International Women's Day"},{3,20,"Международный день счастья","International Day of Happiness"},{3,21,"День борьбы с расовой дискриминацией","Day for Elimination of Racial Discrimination"},{3,22,"Всемирный день водных ресурсов","World Water Day"},{4,7,"Всемирный день здоровья","World Health Day"},{4,22,"Международный день Матери-Земли","International Mother Earth Day"},{5,15,"Международный день семей","International Day of Families"},{6,5,"Всемирный день окружающей среды","World Environment Day"},{6,20,"Всемирный день беженцев","World Refugee Day"},{7,30,"Международный день дружбы","International Day of Friendship"},{8,12,"Международный день молодёжи","International Youth Day"},{9,21,"Международный день мира","International Day of Peace"},{10,1,"Международный день пожилых людей","International Day of Older Persons"},{10,24,"День Организации Объединённых Наций","United Nations Day"},{11,20,"Всемирный день ребёнка","World Children's Day"},{12,3,"Международный день инвалидов","International Day of Persons with Disabilities"},{12,10,"День прав человека","Human Rights Day"}};
    if(s.international)for(const auto& h:international)if(date.m==h.m&&date.d==h.d)out.push_back({key(date),h.ru,"INT",h.en});return out;
}
inline double number(const Json& object,const std::string& field,size_t index,double fallback=std::numeric_limits<double>::quiet_NaN()){auto it=object.find(field);if(it==object.end()||!it->is_array()||index>=it->size()||!(*it)[index].is_number())return fallback;double v=(*it)[index];return std::isfinite(v)?v:fallback;}
inline double temperature(double c,int units){return units==1?c*1.8+32:c;}
inline double windSpeed(double kmh,int units){return units==0?kmh:kmh/1.609344;}
inline double precipitation(double mm,int units){return units==1?mm/25.4:mm;}
inline std::vector<std::pair<int,int>> rainIntervals(const Weather& w,const std::string& date){
    std::vector<std::pair<int,int>> result;auto h=w.details.find("hourly");if(h==w.details.end()||!h->is_object()||!h->contains("time")||!(*h)["time"].is_array())return result;
    Date d=parseDate(date);if(!valid(d))return result;std::string next=key(shift(d,1));
    for(size_t i=0;i<(*h)["time"].size()&&i<300;++i){std::string stamp=(*h)["time"][i];if(stamp.size()<16)continue;int hour=atoi(stamp.substr(11,2).c_str());int end=stamp.substr(0,10)==date?hour:stamp.substr(0,10)==next&&hour==0?24:-1;if(end<=0)continue;
        double amount=number(*h,"rain",i,0)+number(*h,"showers",i,0);if(amount<0.1)continue;int start=end-1;if(!result.empty()&&result.back().second==start)result.back().second=end;else result.push_back({start,end});
    }return result;
}
inline std::string clockTime(int hour,int minute,bool time24,bool suffix=true){char b[24];int h=time24?hour:(hour%12?hour%12:12);snprintf(b,sizeof(b),"%02d:%02d%s",h,minute,!time24&&suffix?(hour<12?" AM":" PM"):"");return b;}
inline const char* weatherName(int c) {if(c==0)return "Ясно";if(c<=3)return "Облачно";if(c==45||c==48)return "Туман";if(c>=51&&c<=67)return "Дождь";if(c>=71&&c<=107)return "Снег";if(c>=80&&c<=82)return "Ливень";if(c==85||c==86)return "Снегопад";if(c>=95)return "Гроза";return "Погода";}
}
