#pragma once
static int musicMenu=0,musicMenuFocus=0,musicMenuScroll=0;static std::string musicMenuTrack,musicEditId,musicAddAfterCreate;
static std::vector<int> musicRowsFor(const std::string& folder){return musicLibrary.rows(musicStatus.files,folder);}
static std::vector<int> musicRows(){return musicRowsFor(musicFolder);}
static void musicPlayRow(int i){auto rows=musicRows();std::vector<std::string> paths;for(int row:rows)paths.push_back(musicStatus.files[row]);music.play(i,musicFolder,paths);}
static std::vector<std::string> musicPlaylists(){std::vector<std::string> folders={""};for(auto& list:musicLibrary.lists)folders.push_back("list:"+list.id);for(const auto& file:musicStatus.files){auto folder=trackFolder(file);if(std::find(folders.begin(),folders.end(),folder)==folders.end())folders.push_back(folder);}return folders;}
static std::string musicPlaylistName(const std::string& folder){if(folder.empty())return t("Все треки","All tracks");if(auto* list=musicLibrary.find(folder))return list->id=="favourites"?t("Избранное","Favorites"):list->title;if(folder=="ux0:data/VitaDay/music")return "VitaDay";if(folder=="ux0:music")return t("Музыка","Music");return folder.substr(folder.find_last_of('/')+1);}
static void musicSelectPlaylist(int i){auto list=musicPlaylists();musicPlaylistFocus=std::clamp(i,0,int(list.size())-1);if(musicFolder!=list[musicPlaylistFocus]){musicFolder=list[musicPlaylistFocus];musicFocus=musicScroll=0;}}
static void openMusic(){musicMenu=0;musicOpen=true;musicFolder=musicStatus.playlist;auto folders=musicPlaylists();auto it=std::find(folders.begin(),folders.end(),musicFolder);musicPlaylistFocus=it==folders.end()?0:int(it-folders.begin());if(it==folders.end())musicFolder.clear();auto rows=musicRows();int currentIndex=musicStatus.index;auto playing=std::find(rows.begin(),rows.end(),currentIndex);musicFocus=playing==rows.end()?0:int(playing-rows.begin());musicActions=rows.empty();musicSidebar=false;}
static void musicToggle(){if(musicStatus.playing){music.pause();return;}if(musicStatus.path.empty()){auto rows=musicRows();if(!rows.empty())musicPlayRow(rows[std::clamp(musicFocus,0,int(rows.size())-1)]);}else if(musicStatus.error||musicStatus.position>=musicStatus.duration-.05)music.restart();else music.pause();}
static void musicNext(int delta){if(musicStatus.path.empty()){auto rows=musicRows();if(!rows.empty())musicPlayRow(delta<0?rows.back():rows.front());}else music.next(delta);}
static std::string musicModeName(){std::string name=musicStatus.mode?t("Перемешивание","Shuffle"):t("По порядку","In order");if(musicStatus.repeat)name+=" · "+std::string(musicStatus.repeat==2?t("Повтор трека","Repeat track"):t("Повтор плейлиста","Repeat playlist"));return name;}
static void musicAction(int i){if(i==0)music.mode();if(i==1)musicNext(-1);if(i==2)musicToggle();if(i==3)musicNext(1);if(i==4)music.repeat();}

static void musicLibraryMenu(){musicMenu=1;musicMenuFocus=musicMenuScroll=0;}
static void musicTrackMenu(){auto rows=musicRows();if(rows.empty()){musicLibraryMenu();return;}musicMenuTrack=musicStatus.files[rows[std::clamp(musicFocus,0,int(rows.size())-1)]];musicMenu=2;musicMenuFocus=musicMenuScroll=0;}
static std::vector<std::pair<int,std::string>> musicMenuItems(){std::vector<std::pair<int,std::string>> items;if(musicMenu==1){items.push_back({10,t("Создать плейлист","Create playlist")});if(musicLibrary.find(musicFolder)&&musicFolder!="list:favourites"){items.push_back({11,t("Переименовать плейлист","Rename playlist")});items.push_back({12,t("Удалить плейлист","Delete playlist")});}items.push_back({13,t("Обновить список","Refresh")});}
 if(musicMenu==2){items.push_back({20,musicLibrary.has("list:favourites",musicMenuTrack)?t("Убрать из избранного","Remove from favorites"):t("В избранное","Add to favorites")});items.push_back({21,t("Добавить в плейлист","Add to playlist")});if(musicLibrary.find(musicFolder)){items.push_back({22,t("Убрать из плейлиста","Remove from playlist")});items.push_back({23,t("Переместить выше","Move up")});items.push_back({24,t("Переместить ниже","Move down")});}items.push_back({25,t("Удалить MP3 с карты","Delete MP3 from card")});}
 if(musicMenu==3){items.push_back({30,t("Создать плейлист","Create playlist")});for(int i=0;i<int(musicLibrary.lists.size());++i)items.push_back({100+i,musicPlaylistName("list:"+musicLibrary.lists[i].id)});}
 if(musicMenu==4||musicMenu==5){items.push_back({40,t("Отмена","Cancel")});items.push_back({41,musicMenu==4?t("Удалить MP3 с карты","Delete MP3 from card"):t("Удалить плейлист","Delete playlist")});}return items;}
static void musicPlaylistNameResult(int kind,const std::string& value){if(value.empty())return;if(kind==6){auto id=musicLibrary.create(value);if(id.empty()){notice=t("Лимит плейлистов: 64","Playlist limit: 64");return;}if(!musicAddAfterCreate.empty()){musicLibrary.add(id,musicAddAfterCreate);musicAddAfterCreate.clear();}musicFolder=id;}else if(auto* list=musicLibrary.find(musicEditId))list->title=value;persistMusicLibrary();auto folders=musicPlaylists();auto it=std::find(folders.begin(),folders.end(),musicFolder);musicPlaylistFocus=it-folders.begin();musicFocus=musicScroll=0;musicSidebar=true;musicMenu=0;}
static void musicMenuAction(){auto items=musicMenuItems();if(items.empty())return;int action=items[std::clamp(musicMenuFocus,0,int(items.size())-1)].first;if(action==10||action==30){musicAddAfterCreate=action==30?musicMenuTrack:"";musicMenu=0;keyboard(6,"",t("Название плейлиста","Playlist name"));return;}if(action==11){musicEditId=musicFolder;auto* list=musicLibrary.find(musicFolder);musicMenu=0;if(list)keyboard(7,list->title,t("Название плейлиста","Playlist name"));return;}if(action==12){musicMenu=5;musicMenuFocus=0;return;}if(action==13)music.refresh();if(action==20){if(musicLibrary.has("list:favourites",musicMenuTrack))musicLibrary.remove("list:favourites",musicMenuTrack);else musicLibrary.add("list:favourites",musicMenuTrack);}if(action==21){musicMenu=3;musicMenuFocus=musicMenuScroll=0;return;}if(action==22)musicLibrary.remove(musicFolder,musicMenuTrack);if(action==23||action==24){musicLibrary.move(musicFolder,musicMenuTrack,action==23?-1:1);auto rows=musicRows();for(int i=0;i<int(rows.size());++i)if(musicStatus.files[rows[i]]==musicMenuTrack)musicFocus=i;}if(action==25){musicMenu=4;musicMenuFocus=0;return;}if(action>=100){int index=action-100;if(index<int(musicLibrary.lists.size()))musicLibrary.add("list:"+musicLibrary.lists[index].id,musicMenuTrack);}if(action==41){if(musicMenu==4){music.removeFile(musicMenuTrack);}else{musicLibrary.erase(musicFolder);musicFolder.clear();musicPlaylistFocus=musicFocus=musicScroll=0;}}
 persistMusicLibrary();musicMenu=0;}
static void musicMenuControls(unsigned b){if(b&SCE_CTRL_CIRCLE){musicMenu=musicMenu==3?2:0;musicMenuFocus=musicMenuScroll=0;return;}auto items=musicMenuItems();if(b&SCE_CTRL_UP)musicMenuFocus=std::max(0,musicMenuFocus-1);if(b&SCE_CTRL_DOWN)musicMenuFocus=std::min(int(items.size())-1,musicMenuFocus+1);if(b&SCE_CTRL_CROSS)musicMenuAction();}
static void drawMusicMenu(){if(!musicMenu)return;auto items=musicMenuItems();if(musicMenuFocus<musicMenuScroll)musicMenuScroll=musicMenuFocus;if(musicMenuFocus>=musicMenuScroll+6)musicMenuScroll=musicMenuFocus-5;rect(0,65,960,479,RGBA8(0,0,0,160));card(245,94,470,(musicMenu>=4?70:49)+std::min(6,int(items.size()))*52+12);fit(266,122,19,musicMenu==4||musicMenu==5?t("Подтвердить удаление","Confirm deletion"):musicMenu==1?t("Плейлисты","Playlists"):musicMenu==3?t("Добавить в плейлист","Add to playlist"):trackName(musicMenuTrack),426,p.ink);if(musicMenu==4||musicMenu==5)fit(266,148,13,musicMenu==4?trackName(musicMenuTrack):musicPlaylistName(musicFolder),426,p.muted);int top=musicMenu>=4?164:143;for(int n=0;n<6&&musicMenuScroll+n<int(items.size());++n){int row=musicMenuScroll+n,y=top+n*52;bool selected=row==musicMenuFocus;if(selected)outline(260,y,440,46,p.accent,1);int action=items[row].first;fit(276,y+29,17,items[row].second,408,action==25||action==12||action==41?RGBA8(241,107,105,255):selected?p.accent:p.ink);}drawScrollBar(705,top,312,items.size(),6,musicMenuScroll);}
struct MusicTarget{int id,x,y;};
static void musicMove(unsigned b){int dx=b&SCE_CTRL_LEFT?-1:b&SCE_CTRL_RIGHT?1:0,dy=b&SCE_CTRL_UP?-1:b&SCE_CTRL_DOWN?1:0;if(!dx&&!dy)return;
 auto folders=musicPlaylists();auto rows=musicRows();
 // Horizontal input switches list panes; the transport is reached vertically.
 if(!musicActions&&dx){if(musicSidebar&&dx>0&&!rows.empty()){musicSidebar=false;musicFocus=std::clamp(musicFocus,0,int(rows.size())-1);}else if(!musicSidebar&&dx<0)musicSidebar=true;return;}
 if(musicActions){if(dx){musicActionFocus=std::clamp(musicActionFocus+dx,0,4);return;}if(dy<0){musicActions=false;musicSidebar=rows.empty();if(!rows.empty())musicFocus=std::clamp(musicFocus,0,int(rows.size())-1);}return;}
if(musicFocus<musicScroll)musicScroll=musicFocus;if(musicFocus>=musicScroll+6)musicScroll=musicFocus-5;if(musicPlaylistFocus<musicPlaylistScroll)musicPlaylistScroll=musicPlaylistFocus;if(musicPlaylistFocus>=musicPlaylistScroll+6)musicPlaylistScroll=musicPlaylistFocus-5;std::vector<MusicTarget> targets;for(int n=0;n<6&&musicPlaylistScroll+n<int(folders.size());++n)targets.push_back({1000+musicPlaylistScroll+n,144,148+n*48});for(int n=0;n<6&&musicScroll+n<int(rows.size());++n)targets.push_back({2000+musicScroll+n,613,150+n*46});int centers[]={391,447,503,559,615};for(int i=0;i<5;++i)targets.push_back({3000+i,centers[i],448});
 int id=musicActions?3000+musicActionFocus:musicSidebar?1000+musicPlaylistFocus:2000+musicFocus;auto current=std::find_if(targets.begin(),targets.end(),[&](const MusicTarget& t){return t.id==id;});
 // Lists continue beyond the visible window before moving to a neighbouring pane.
 if(!dx&&dy&&musicSidebar){int next=musicPlaylistFocus+dy;if(next>=0&&next<int(folders.size())){musicSelectPlaylist(next);return;}if(dy<0)return;}
 if(!dx&&dy&&!musicActions&&!musicSidebar){int next=musicFocus+dy;if(next>=0&&next<int(rows.size())){musicFocus=next;return;}if(dy<0)return;}
 if(current==targets.end())return;double best=1e12;int chosen=id;for(const auto& t:targets){double x=t.x-current->x,y=t.y-current->y,along=x*dx+y*dy,across=std::abs(x*dy-y*dx);if(along<=0)continue;double score=along+across*1.5;if(score<best){best=score;chosen=t.id;}}
 musicActions=chosen>=3000;musicSidebar=chosen>=1000&&chosen<2000;if(musicActions)musicActionFocus=chosen-3000;else if(musicSidebar)musicSelectPlaylist(chosen-1000);else musicFocus=chosen-2000;
}
static void musicControls(unsigned b,bool right=false){if(musicMenu){musicMenuControls(b);return;}if(b&SCE_CTRL_CIRCLE){musicOpen=false;return;}if(right){if(b&SCE_CTRL_LEFT)music.seek(-5);if(b&SCE_CTRL_RIGHT)music.seek(5);return;}if(b&SCE_CTRL_TRIANGLE)musicToggle();if(b&SCE_CTRL_SELECT){musicLibraryMenu();return;}if(b&SCE_CTRL_SQUARE){musicTrackMenu();return;}
 musicMove(b);if(b&SCE_CTRL_CROSS){if(musicActions)musicAction(musicActionFocus);else if(musicSidebar){musicSelectPlaylist(musicPlaylistFocus);musicFocus=0;}else{auto rows=musicRows();if(!rows.empty())musicPlayRow(rows[std::clamp(musicFocus,0,int(rows.size())-1)]);}}
}
static void musicScrollInput(int steps,int startX){if(musicMenu){musicMenuFocus=std::clamp(musicMenuFocus+steps,0,std::max(0,int(musicMenuItems().size())-1));return;}if(startX>=0&&startX<274){musicSidebar=true;musicSelectPlaylist(musicPlaylistFocus+steps);}else{musicSidebar=false;musicFocus=std::clamp(musicFocus+steps,0,std::max(0,int(musicRows().size())-1));}musicActions=false;}
static unsigned musicTint(double amount){unsigned result=0xff000000u;for(int channel=0;channel<3;++channel){int shift=channel*8;unsigned a=(p.card>>shift)&255,b=(p.accent>>shift)&255;result|=unsigned(a*(1-amount)+b*amount)<<shift;}return result;}
static unsigned musicIconInk(){int luma=((p.accent&255)*299+((p.accent>>8)&255)*587+((p.accent>>16)&255)*114)/1000;return luma>145?RGBA8(16,23,19,255):RGBA8(250,250,250,255);}
static std::string musicAlbum(const std::string& path){auto folder=trackFolder(path);return folder.empty()?"MP3":"MP3 · "+musicPlaylistName(folder);}
static void musicTouch(int x,int y){if(musicMenu){int top=musicMenu>=4?164:143;auto items=musicMenuItems();if(x>=260&&x<=700&&y>=top&&y<top+312){int row=musicMenuScroll+(y-top)/52;if(row<int(items.size())){musicMenuFocus=row;musicMenuAction();}}return;}if(x>=223&&x<=265&&y>=88&&y<=124){musicLibraryMenu();return;}if(y<65)return;if(y>=484&&y<=506&&x>=303&&x<=703&&musicStatus.duration>0){music.seekTo((x-303)/400.*musicStatus.duration);return;}if(y>=89&&y<=122&&x>=900&&x<=940){music.refresh();return;}if(y>=424&&y<=476){int centers[]={391,447,503,559,615};for(int i=0;i<5;++i)if(std::abs(x-centers[i])<=24){musicActionFocus=i;musicActions=true;musicAction(i);return;}}if(y>=126&&y<414&&x>=28&&x<274){musicSidebar=true;musicActions=false;musicSelectPlaylist(musicPlaylistScroll+(y-126)/48);return;}if(y>=129&&y<405&&x>=286&&x<940){auto rows=musicRows();int index=musicScroll+(y-129)/46;if(index<int(rows.size())){musicFocus=index;musicActions=musicSidebar=false;if(x>=900)musicTrackMenu();else musicPlayRow(rows[index]);}}}
static int musicHeaderTimelineX=27;
static bool musicTimelineTouch(int x,int y){return (musicStatus.duration>0&&y>=46&&y<=55&&x>=musicHeaderTimelineX&&x<=190)||(musicOpen&&!musicMenu&&musicStatus.duration>0&&y>=484&&y<=506&&x>=303&&x<=703);}
static std::string musicRemainingTime(){return "−"+musicTime(std::max(0.,musicStatus.duration-musicStatus.position));}
static void drawMusicHeader(){drawRoundedCard(16,10,312,45,p.card);bool cover=drawEmbeddedMusicCover(24,16,28);int titleX=cover?59:27,titleWidth=cover?131:163;fit(titleX,25,14,musicStatus.path.empty()?t("Музыка","Music"):musicStatus.title.empty()?trackName(musicStatus.path):musicStatus.title,titleWidth,p.ink);fit(titleX,38,10,musicStatus.artist,titleWidth,p.muted);musicHeaderTimelineX=titleX;fit(titleX,48,9,musicStatus.path.empty()?"MP3":musicTime(musicStatus.position),titleWidth/2-3,p.muted);if(!musicStatus.path.empty()){auto remaining=fitLabel(musicRemainingTime(),9,titleWidth/2-3,9,textWidth);text(190-textWidth(remaining.size,remaining.value),48,remaining.size,remaining.value,p.muted);}double progress=std::clamp(musicStatus.duration>0?musicStatus.position/musicStatus.duration:0.,0.,1.);rect(titleX,51,titleWidth,2,p.line);rect(titleX,51,titleWidth*progress,2,p.accent);if(musicOpen)outline(16,10,312,45,p.accent,1);const char* icons[]={"previous",musicStatus.playing?"pause":"play","next"};for(int i=0;i<3;++i){int x=211+i*42;bool focus=!musicOpen&&page==0&&homeFocus==401+i&&homeBlock<0;if(focus)drawSmoothCircle(x,32,18,p.accent);if(i==1)drawSmoothCircle(x,32,16,p.accent);drawMusicIcon(icons[i],x,32,24,i==1||focus?musicIconInk():p.ink);}if(!musicOpen&&page==0&&homeFocus==400&&homeBlock<0)outline(21,14,174,37,p.accent,1);}
static void drawMusicCover(int x,int y,int size){if(drawEmbeddedMusicCover(x,y,size))return;for(int row=0;row<size;++row)rect(x,y+row,size,1,musicTint(.8-.45*row/std::max(1,size-1)));float scale=size/200.f,cx=x+size/2.f,cy=y+size/2.f;drawSmoothCircle(cx,cy,73*scale,musicTint(.12));drawSmoothCircle(cx,cy,55*scale,musicTint(.3));drawSmoothCircle(cx,cy,39*scale,musicTint(.12));rect(cx,cy-33*scale,std::max(2.f,5*scale),59*scale,p.accent);rect(cx,cy-33*scale,30*scale,std::max(2.f,6*scale),p.accent);drawSmoothCircle(cx-8*scale,cy+25*scale,12*scale,p.accent);}
static void drawMusic(){
 auto folders=musicPlaylists();musicPlaylistFocus=std::clamp(musicPlaylistFocus,0,int(folders.size())-1);if(std::find(folders.begin(),folders.end(),musicFolder)==folders.end())musicSelectPlaylist(0);auto rows=musicRows();card(20,82,254,332);fit(38,113,20,t("Плейлисты","Playlists"),185,p.ink);rect(241,98,2,16,p.accent);rect(234,105,16,2,p.accent);if(musicPlaylistFocus<musicPlaylistScroll)musicPlaylistScroll=musicPlaylistFocus;if(musicPlaylistFocus>=musicPlaylistScroll+6)musicPlaylistScroll=musicPlaylistFocus-5;musicPlaylistScroll=std::min(musicPlaylistScroll,std::max(0,int(folders.size())-6));
 for(int n=0;n<6&&musicPlaylistScroll+n<int(folders.size());++n){int i=musicPlaylistScroll+n,y=126+n*48;bool active=folders[i]==musicFolder;if(active)rect(30,y,228,43,p.line);fit(42,y+23,16,musicPlaylistName(folders[i]),202,active?p.accent:p.ink);fit(42,y+39,11,std::string(t("Треки","Tracks"))+": "+std::to_string(musicRowsFor(folders[i]).size()),202,p.muted);if(musicSidebar&&!musicActions&&i==musicPlaylistFocus)outline(30,y,228,43,p.accent,1);}drawScrollBar(265,126,288,folders.size(),6,musicPlaylistScroll);
 fit(306,113,20,musicPlaylistName(musicFolder),425,p.ink);{fit(778,112,12,std::string(t("Треки","Tracks"))+": "+std::to_string(rows.size()),122,p.muted);drawMusicIcon("refresh",918,106,24,p.muted);}musicFocus=std::clamp(musicFocus,0,std::max(0,int(rows.size())-1));if(musicFocus<musicScroll)musicScroll=musicFocus;if(musicFocus>=musicScroll+6)musicScroll=musicFocus-5;musicScroll=std::min(musicScroll,std::max(0,int(rows.size())-6));
 for(int n=0;n<6&&musicScroll+n<int(rows.size());++n){int row=musicScroll+n,index=rows[row],y=129+n*46;card(286,y,654,42);bool current=index==musicStatus.index;if(current&&musicStatus.playing){for(int i=0;i<3;++i){float height=5+15*(.5+.5*std::sin(musicStatus.position*(7.1+i*.9)+i*2.3));rect(306+i*6,y+30-height,3,height,p.accent);}}else fit(302,y+27,13,std::to_string(row+1),32,p.muted);auto tags=index<int(musicStatus.tags.size())?musicStatus.tags[index]:MusicTags{};fit(342,y+19,17,tags.title.empty()?trackName(musicStatus.files[index]):tags.title,548,current?p.accent:p.ink);fit(342,y+35,11,tags.artist,548,p.muted);for(int dot=0;dot<3;++dot)drawSmoothCircle(907+dot*6,y+21,2,p.muted);if(!musicSidebar&&!musicActions&&row==musicFocus)outline(286,y,654,42,p.accent,1);}drawScrollBar(946,129,276,rows.size(),6,musicScroll);
 if(rows.empty()&&!musicStatus.loading){fit(306,188,18,t("Скопируй MP3 в папку:","Copy MP3 files to:"),612,p.ink);fit(306,221,17,"ux0:data/VitaDay/music",612,p.accent);fit(306,250,17,"ux0:music",612,p.accent);fit(306,289,14,t("Затем обнови список","Then refresh the list"),612,p.muted);}
 card(20,418,920,92);drawMusicCover(36,436,54);fit(104,458,17,musicStatus.path.empty()?t("Музыка","Music"):musicStatus.title.empty()?trackName(musicStatus.path):musicStatus.title,208,p.ink);fit(104,477,11,musicStatus.error==1?t("Не удалось прочитать MP3","Cannot read MP3"):musicStatus.error==2?t("Аудиовыход недоступен","Audio output unavailable"):musicStatus.error==3?t("Не удалось удалить MP3","Could not delete MP3"):musicStatus.loading?t("Загрузка…","Loading…"):musicStatus.artist,208,p.muted);
 const char* icons[]={"shuffle","previous",musicStatus.playing?"pause":"play","next",musicStatus.repeat==2?"repeat-one":"repeat"};int centers[]={391,447,503,559,615};for(int i=0;i<5;++i){int x=centers[i];bool focus=musicActions&&musicActionFocus==i,active=(i==0&&musicStatus.mode)||(i==4&&musicStatus.repeat);if(i==2){if(focus)drawSmoothCircle(x,448,26,p.accent);drawSmoothCircle(x,448,24,p.ink);}else if(focus)drawSmoothCircle(x,448,21,p.line);drawMusicIcon(icons[i],x,448,i==2?28:28,i==2?(p.card|0xff000000u):active?p.accent:focus?p.ink:p.muted);if(active)drawSmoothCircle(x,471,2,p.accent);}
 double fraction=std::clamp(musicStatus.duration>0?musicStatus.position/musicStatus.duration:0.,0.,1.);rect(303,492,400,4,p.line);rect(303,492,400*fraction,4,p.accent);drawSmoothCircle(303+400*fraction,494,3,p.ink);fit(303,484,11,musicTime(musicStatus.position),104,p.muted);auto remaining=fitLabel(musicRemainingTime(),11,104,11,textWidth);text(703-textWidth(remaining.size,remaining.value),484,remaining.size,remaining.value,p.muted);drawMusicMenu();
}
