#pragma once
#include <string>
#include <vector>
#include <cstdio>
#include <cstdint>
namespace day {
struct MusicTags {std::string title,artist;};
inline void musicUtf8(std::string& out,uint32_t c){if(c<32||c==127)return;if(c<128)out+=char(c);else if(c<2048){out+=char(0xc0|(c>>6));out+=char(0x80|(c&63));}else if(c<65536){out+=char(0xe0|(c>>12));out+=char(0x80|((c>>6)&63));out+=char(0x80|(c&63));}else if(c<=0x10ffff){out+=char(0xf0|(c>>18));out+=char(0x80|((c>>12)&63));out+=char(0x80|((c>>6)&63));out+=char(0x80|(c&63));}}
inline std::string musicTagText(const unsigned char* data,size_t size){if(size<2||size>4096)return {};unsigned encoding=*data++;--size;std::string out;if(encoding==0){for(size_t i=0;i<size&&data[i];++i)musicUtf8(out,data[i]);}else if(encoding==3){for(size_t i=0;i<size&&data[i];++i)if(data[i]>=32)out+=char(data[i]);}else if(encoding==1||encoding==2){bool little=false;size_t i=0;if(size>=2&&data[0]==255&&data[1]==254){little=true;i=2;}else if(size>=2&&data[0]==254&&data[1]==255)i=2;auto unit=[&](size_t n){return uint32_t(little?data[n]|(data[n+1]<<8):(data[n]<<8)|data[n+1]);};for(;i+1<size;i+=2){uint32_t c=unit(i);if(!c)break;if(c>=0xd800&&c<=0xdbff&&i+3<size){uint32_t d=unit(i+2);if(d>=0xdc00&&d<=0xdfff){c=0x10000+((c-0xd800)<<10)+(d-0xdc00);i+=2;}else c=0xfffd;}else if(c>=0xd800&&c<=0xdfff)c=0xfffd;musicUtf8(out,c);}}while(!out.empty()&&out.back()==' ')out.pop_back();return out;}
inline uint32_t musicTagSize(const unsigned char* p,bool sync){return sync?((p[0]&127)<<21)|((p[1]&127)<<14)|((p[2]&127)<<7)|(p[3]&127):(uint32_t(p[0])<<24)|(uint32_t(p[1])<<16)|(uint32_t(p[2])<<8)|p[3];}
inline MusicTags parseMusicTag(const std::vector<unsigned char>& data,int version,unsigned flags){MusicTags result;if(version<2||version>4)return result;size_t offset=0;if(flags&64){if(data.size()<4)return result;uint32_t skip=musicTagSize(data.data(),version==4);offset=version==3?size_t(skip)+4:skip;if(offset>data.size())return result;}size_t header=version==2?6:10;while(offset+header<=data.size()){auto p=data.data()+offset;if(!p[0])break;std::string id(reinterpret_cast<const char*>(p),version==2?3:4);uint32_t n=version==2?(uint32_t(p[3])<<16)|(uint32_t(p[4])<<8)|p[5]:musicTagSize(p+4,version==4);offset+=header;if(n>data.size()-offset)break;bool plain=version==2||(version==3?(p[9]&0xe0)==0:(p[9]&0x4d)==0);if(plain&&(id=="TIT2"||id=="TT2"||id=="TPE1"||id=="TP1")){std::vector<unsigned char> text(data.begin()+offset,data.begin()+offset+n);if((flags&128)||(version==4&&(p[9]&2))){for(size_t i=0;i+1<text.size();++i)if(text[i]==255&&text[i+1]==0)text.erase(text.begin()+i+1);}auto value=musicTagText(text.data(),text.size());if(id=="TIT2"||id=="TT2")result.title=value;else result.artist=value;}offset+=n;}return result;}
inline MusicTags readMusicTags(const std::string& path){MusicTags result;FILE* f=fopen(path.c_str(),"rb");if(!f)return result;unsigned char head[10]{};if(fread(head,1,10,f)==10&&head[0]=='I'&&head[1]=='D'&&head[2]=='3'){uint32_t size=musicTagSize(head+6,true);if(size<=8*1024*1024){std::vector<unsigned char> data;int version=head[3];uint32_t remaining=size;unsigned flags=head[5];if((flags&128)&&version<4){data.resize(size);if(fread(data.data(),1,size,f)==size){size_t write=0;for(size_t i=0;i<data.size();++i){auto c=data[i];data[write++]=c;if(c==255&&i+1<data.size()&&data[i+1]==0)++i;}data.resize(write);result=parseMusicTag(data,version,flags&~128u);}}else if(version>=2&&version<=4){if(flags&64){unsigned char ext[4];if(remaining>=4&&fread(ext,1,4,f)==4){uint32_t skip=musicTagSize(ext,version==4)+(version==3?4:0);if(skip>=4&&skip<=remaining&&fseek(f,skip-4,SEEK_CUR)==0)remaining-=skip;else remaining=0;}else remaining=0;}size_t header=version==2?6:10;for(int frames=0;frames<1024&&remaining>=header;++frames){unsigned char h[10]{};if(fread(h,1,header,f)!=header||!h[0])break;remaining-=header;uint32_t n=version==2?(uint32_t(h[3])<<16)|(uint32_t(h[4])<<8)|h[5]:musicTagSize(h+4,version==4);if(n>remaining)break;std::string id((const char*)h,version==2?3:4);bool text=id=="TIT2"||id=="TT2"||id=="TPE1"||id=="TP1";if(text&&n<=4096){size_t before=data.size();data.insert(data.end(),h,h+header);data.resize(data.size()+n);if(fread(data.data()+before+header,1,n,f)!=n){data.resize(before);break;}}else if(fseek(f,n,SEEK_CUR)!=0)break;remaining-=n;}result=parseMusicTag(data,version,flags&~64u);}}}if((result.title.empty()||result.artist.empty())&&fseek(f,-128,SEEK_END)==0){unsigned char v1[128]{};if(fread(v1,1,128,f)==128&&v1[0]=='T'&&v1[1]=='A'&&v1[2]=='G'){unsigned char text[31]{};for(int field=0;field<2;++field){for(int i=0;i<30;++i)text[i+1]=v1[3+field*30+i];auto value=musicTagText(text,31);if(field==0&&result.title.empty())result.title=value;if(field==1&&result.artist.empty())result.artist=value;}}}fclose(f);return result;}
}
