#pragma once
#include "music_tags.hpp"
#include <algorithm>
namespace day {
struct MusicArtwork{std::vector<unsigned char> bytes;bool png=false;int type=-1;};
inline void musicDeunsync(std::vector<unsigned char>& data){size_t write=0;for(size_t i=0;i<data.size();++i){unsigned char c=data[i];data[write++]=c;if(c==255&&i+1<data.size()&&data[i+1]==0)++i;}data.resize(write);}
inline MusicArtwork parseMusicArtwork(const std::vector<unsigned char>& data,int version,unsigned flags){MusicArtwork best;if(version<2||version>4||(version==2&&(flags&64)))return best;size_t offset=0;if(flags&64){if(data.size()<4)return best;offset=musicTagSize(data.data(),version==4)+(version==3?4:0);}size_t header=version==2?6:10;while(offset+header<=data.size()){auto* p=data.data()+offset;if(!p[0])break;std::string id((const char*)p,version==2?3:4);uint32_t n=version==2?(uint32_t(p[3])<<16)|(uint32_t(p[4])<<8)|p[5]:musicTagSize(p+4,version==4);offset+=header;if(n>data.size()-offset)break;bool plain=version==2||(version==3?(p[9]&0xe0)==0:(p[9]&0x4d)==0);if(plain&&(id=="APIC"||id=="PIC")&&n>=6&&n<=8*1024*1024){std::vector<unsigned char> image(data.begin()+offset,data.begin()+offset+n);if((flags&128)||(version==4&&(p[9]&2)))musicDeunsync(image);size_t pos=1;unsigned encoding=image[0];if(version==2)pos+=3;else{while(pos<image.size()&&image[pos])++pos;++pos;}if(pos>=image.size()){offset+=n;continue;}int type=image[pos++];bool terminated=false;if(encoding==1||encoding==2){for(;pos+1<image.size();pos+=2)if(image[pos]==0&&image[pos+1]==0){pos+=2;terminated=true;break;}}else{while(pos<image.size()&&image[pos])++pos;if(pos<image.size()){++pos;terminated=true;}}if(terminated&&pos<image.size()){bool png=image.size()-pos>=8&&image[pos]==137&&image[pos+1]=='P'&&image[pos+2]=='N'&&image[pos+3]=='G',jpeg=image.size()-pos>=3&&image[pos]==255&&image[pos+1]==216&&image[pos+2]==255;if((png||jpeg)&&(best.bytes.empty()||(type==3&&best.type!=3))){best.bytes.assign(image.begin()+pos,image.end());best.png=png;best.type=type;}}}offset+=n;}return best;}
inline MusicArtwork readMusicArtwork(const std::string& path){FILE* f=fopen(path.c_str(),"rb");if(!f)return {};unsigned char head[10]{};MusicArtwork result;if(fread(head,1,10,f)==10&&head[0]=='I'&&head[1]=='D'&&head[2]=='3'){uint32_t size=musicTagSize(head+6,true);if(size<=8*1024*1024){std::vector<unsigned char> data(size);if(fread(data.data(),1,size,f)==size){unsigned flags=head[5];if((flags&128)&&head[3]<4){musicDeunsync(data);flags&=~128u;}result=parseMusicArtwork(data,head[3],flags);}}}fclose(f);return result;}
}
