#pragma once
// Included after platform input/render helpers; all layout coordinates are Vita pixels.
static const Weather& viewWeather(){return weatherRegion>=0&&weatherRegion<(int)state.regions.size()?state.regions[weatherRegion].weather:state.weather;}
static const Location& viewLocation(){return weatherRegion>=0&&weatherRegion<(int)state.regions.size()?state.regions[weatherRegion].location:state.location;}
static Date forecastToday(){auto l=viewLocation();auto n=clockAt(zoneOffset(zoneRules(),l.zone,utcNow(),l.offset));return {n.year,n.month,n.day};}
static std::string numeric(double n,int decimals=0){if(!std::isfinite(n))return "—";char s[48];snprintf(s,sizeof(s),"%.*f",std::clamp(decimals,0,2),n);return s;}
static std::string temp(double c,bool unit=false){return numeric(temperature(c,state.units))+ (unit?(state.units?"°F":"°C"):"°");}
static std::string wind(double kmh){return numeric(windSpeed(kmh,state.units))+t(state.units?" mph":" км/ч",state.units?" mph":" km/h");}
static std::string rainIn(double mm,int units){double v=precipitation(mm,units);if(units&&v>0&&v<0.01)return "<0.01 in";return numeric(v,units?2:1)+(units?" in":t(" мм"," mm"));}
static std::string rain(double mm){return rainIn(mm,state.units);}
[[maybe_unused]] static std::string weatherLabel(int c){if(!state.language)return weatherName(c);if(c==0)return "Clear";if(c<=3)return "Cloudy";if(c==45||c==48)return "Fog";if(c>=51&&c<=67)return "Rain";if(c>=71&&c<=77)return "Snow";if(c>=80&&c<=82)return "Showers";if(c==85||c==86)return "Snow showers";if(c>=95)return "Thunderstorm";return "Weather";}
static const Json& daily(){static const Json empty=Json::object();auto it=viewWeather().details.find("daily");return it!=viewWeather().details.end()&&it->is_object()?*it:empty;}
static const Json& hourly(){static const Json empty=Json::object();auto it=viewWeather().details.find("hourly");return it!=viewWeather().details.end()&&it->is_object()?*it:empty;}
static std::string stringAt(const Json& j,const char* field,int index){auto it=j.find(field);return it!=j.end()&&it->is_array()&&index>=0&&index<(int)it->size()&&(*it)[index].is_string()?(*it)[index].get<std::string>():"";}
static std::vector<int> hoursForDay(int d){std::vector<int> out;if(d<0||d>=(int)viewWeather().dates.size())return out;auto it=hourly().find("time");if(it==hourly().end()||!it->is_array())return out;for(size_t i=0;i<it->size()&&i<300;++i){std::string stamp=(*it)[i];if(stamp.substr(0,10)==viewWeather().dates[d])out.push_back(i);}if(!out.empty()){int next=out.back()+1;if(next<(int)it->size()&&(*it)[next].get<std::string>().substr(11,5)=="00:00")out.push_back(next);}return out;}
static std::string stampTime(const std::string& stamp){if(stamp.size()<16)return "—";int h=atoi(stamp.substr(11,2).c_str()),m=atoi(stamp.substr(14,2).c_str());return clockTime(h,m,state.time24);}
static std::string holidayTitle(const Holiday& h){return h.country=="USR"?h.name:localizedHolidayTitle(h,state.language);}
static std::vector<Country> catalog(){if(!state.catalog.empty())return state.catalog;return {{"US","United States",1},{"GB","United Kingdom",2},{"DE","Germany",3},{"FR","France",4},{"IT","Italy",5},{"ES","Spain",6},{"CA","Canada",7},{"AU","Australia",8},{"JP","Japan",1},{"RU","Russia",2},{"UA","Ukraine",3},{"PL","Poland",4},{"NL","Netherlands",5},{"BE","Belgium",6},{"PT","Portugal",7},{"BR","Brazil",8},{"MX","Mexico",1},{"AT","Austria",2},{"CH","Switzerland",3},{"SE","Sweden",4},{"NO","Norway",5},{"FI","Finland",6},{"DK","Denmark",7},{"CZ","Czechia",8}};}
static std::string countryName(const Country& c){if(state.language)return englishCountries.value(c.code,c.name);static const std::map<std::string,std::string> names={{"US","США"},{"GB","Великобритания"},{"DE","Германия"},{"FR","Франция"},{"IT","Италия"},{"ES","Испания"},{"CA","Канада"},{"AU","Австралия"},{"JP","Япония"},{"RU","Россия"},{"UA","Украина"},{"PL","Польша"},{"NL","Нидерланды"},{"BE","Бельгия"},{"PT","Португалия"},{"BR","Бразилия"},{"MX","Мексика"},{"AT","Австрия"},{"CH","Швейцария"},{"SE","Швеция"},{"NO","Норвегия"},{"FI","Финляндия"},{"DK","Дания"},{"CZ","Чехия"}};auto it=names.find(c.code);return it!=names.end()?it->second:localizedCountries.value(c.code,c.name);}
[[maybe_unused]] static void windIcon(int x,int y,float scale=1,unsigned color=0){drawAssetIcon(x,y,3,std::max(12,(int)(24*scale)),color?color:p.accent);}
static void weatherIcon(int x,int y,int code,int radius=9){int kind=code==0?9:code<=2?10:code==3?5:code==45||code==48?13:(code>=71&&code<=77)||code==85||code==86?12:code>=95?14:11;unsigned color=kind==9||kind==10?RGBA8(244,169,61,255):kind==11?RGBA8(55,154,238,255):kind==12?RGBA8(70,181,216,255):kind==14?RGBA8(221,137,232,255):p.muted;drawAssetIcon(x,y,kind,radius<=6?24:32,color);}
static unsigned metricColor(int metric){static const unsigned c[]={RGBA8(244,156,56,255),RGBA8(73,162,246,255),RGBA8(59,187,185,255),RGBA8(148,131,237,255),RGBA8(220,116,172,255),RGBA8(122,157,190,255)};return c[metric%6];}
static void infoIcon(int x,int y,int kind,unsigned color){drawAssetIcon(x,y,kind,24,color);}
static void outline(int x,int y,int w,int h,unsigned c,int thickness=2){rect(x,y,w,thickness,c);rect(x,y+h-thickness,w,thickness,c);rect(x,y,thickness,h,c);rect(x+w-thickness,y,thickness,h,c);}
static void card(int x,int y,int w,int h){for(int row=0;row<h;++row){int edge=std::min(row,h-1-row);int inset=edge>=8?0:(int)std::ceil(8-std::sqrt(64.f-(8-edge-0.5f)*(8-edge-0.5f)));rect(x+inset,y+row,w-inset*2,1,p.card);}}
static std::string valueIn(double n,int metric,int units){return metric==0?numeric(temperature(n,units))+ (units?"°F":"°C"):metric==1?rainIn(n,units):metric==3?numeric(windSpeed(n,units))+(units?" mph":t(" км/ч"," km/h")):metric==4?(units?numeric(n/33.8638866667,2)+" inHg":numeric(n)+" hPa"):numeric(n)+"%";}
static void dualValue(int x,int y,double n,int metric,int size,int width=220){fit(x,y,size,valueIn(n,metric,state.units),width,metricColor(metric));if(state.dualUnits&&(metric==0||metric==1||metric==3||metric==4))fit(x,y+20,13,valueIn(n,metric,1-state.units),width,p.muted);}
static std::vector<std::string> zonesFor(const std::string& code){auto it=timeZones.find("countries");if(it==timeZones.end()||!it->contains(code))return {};return (*it)[code].get<std::vector<std::string>>();}
static std::string zoneFor(const Country& c){auto zones=zonesFor(c.code);if(!c.zone.empty()&&std::find(zones.begin(),zones.end(),c.zone)!=zones.end())return c.zone;return defaultZone(c.code,zones);}
static std::string zoneCity(std::string zone){auto pos=zone.rfind('/');if(pos!=std::string::npos)zone=zone.substr(pos+1);std::replace(zone.begin(),zone.end(),'_',' ');return zone;}
static std::string cityName(const Location& l){const std::string& translated=state.language?l.cityEn:l.cityRu;if(!translated.empty())return translated;auto it=cityNames.find(l.zone);if(it!=cityNames.end()&&(l.city.empty()||l.city==zoneCity(l.zone)||l.city==it->value("ru",std::string{})||l.city==it->value("en",std::string{})))return it->value(state.language?"en":"ru",l.city);return l.city;}
static std::string countryCity(const Country& c){for(const auto& place:state.regions)if(place.location.country==c.code&&place.location.zone==zoneFor(c)&&(c.clockCity.empty()||c.clockCity==place.location.city))return cityName(place.location);Location l;l.zone=zoneFor(c);l.city=c.clockCity;return cityName(l);}
static SceDateTime countryClock(const Country& c){return clockAt(zoneOffset(zoneRules(),zoneFor(c),utcNow()));}
static std::vector<Country> trackedClocks(){std::vector<Country> out;for(const auto& c:state.countries)if(c.clock){bool rootFound=false;for(const auto& place:state.regions)if(countryPlace(c,place.location)||(place.origin==3&&place.location.country==c.code)){rootFound|=countryPlace(c,place.location);if(place.clock){auto city=c;city.zone=place.location.zone;city.clockCity=place.location.city;city.cityPinned=true;city.cityLat=place.location.lat;city.cityLon=place.location.lon;out.push_back(city);}}if(c.cityEnabled&&!rootFound)out.push_back(c);}return out;}

static void clockWeather(int x,int y,int width,bool vertical){
    if(!state.weather.valid){fit(x,y+23,14,"—",width,p.muted);return;}
    if(vertical){weatherIcon(x+width/2,y+16,state.weather.code,9);std::string primary=temp(state.weather.temperature,true);int size=22;while(size>16&&textWidth(size,primary)>width) --size;fit(x+std::max(0,(width-textWidth(size,primary))/2),y+51,size,primary,width,metricColor(0));if(state.dualUnits){auto secondary=valueIn(state.weather.temperature,0,1-state.units);fit(x+std::max(0,(width-textWidth(12,secondary))/2),y+69,12,secondary,width,p.muted);}}
    else{weatherIcon(x+16,y+16,state.weather.code,9);auto primary=temp(state.weather.temperature,true);fit(x+40,y+23,20,primary,width-40,metricColor(0));if(state.dualUnits){int next=x+48+textWidth(20,primary);fit(next,y+23,12,valueIn(state.weather.temperature,0,1-state.units),x+width-next,p.muted);}}
}
static std::vector<Holiday> calendarObservances(Date date){auto list=holidayItems(state,date);auto marks=marksFor(state,date);for(auto it=marks.rbegin();it!=marks.rend();++it){const auto& title=it->second.title;list.insert(list.begin(),{key(date),title.empty()?t("Своя дата","Personal date"):title,"USR",title.empty()?"Personal date":title});}return list;}
static void openCalendarText(const std::string& value){if(value.empty())return;readerText=value;readerScroll=0;calendarReader=true;}
static void readSelectedText(){auto marks=marksFor(state,selected);if(!marks.empty()&&!marks.front().second.title.empty())openCalendarText(marks.front().second.title);else{auto h=holidayItems(state,selected);if(!h.empty())openCalendarText(holidayTitle(h[std::clamp(holidayScroll,0,(int)h.size()-1)]));}}
static void scrollCalendarText(int delta){auto lines=textLines(readerText,24,804);readerScroll=std::clamp(readerScroll+delta,0,std::max(0,(int)lines.size()-9));}
static void drawCalendarText(const std::string& title=""){card(28,82,904,424);fit(52,119,22,title.empty()?dateWords(selected):title,770,p.accent);text(884,119,22,"×",p.muted);auto lines=textLines(readerText,24,804);scrollCalendarText(0);for(int i=0;i<9&&readerScroll+i<(int)lines.size();++i)fit(64,171+i*34,24,lines[readerScroll+i],804);if(lines.size()>9){rect(903,144,3,309,p.line);int height=std::max(24,309*9/(int)lines.size());rect(902,144+readerScroll*(309-height)/((int)lines.size()-9),5,height,p.accent);fit(64,484,12,std::to_string(readerScroll+1)+"–"+std::to_string(std::min(readerScroll+9,(int)lines.size()))+" / "+std::to_string(lines.size()),240,p.muted);}}
static void clockFace(){
    auto n=now();auto clocks=trackedClocks();clockScroll=std::clamp(clockScroll,0,clocks.empty()?0:((int)clocks.size()-1)/8*8);bool compact=!clocks.empty();int h=state.time24?n.hour:(n.hour%12?n.hour%12:12);std::string value=clockTime(n.hour,n.minute,state.time24,false);Date d=today();rect(28,82,550,296,p.card);fit(state.style==2? (compact?268:332):52,state.style==2?115:104,18,cityName(state.location),state.style==2?225:state.style==1&&compact?190:470,p.muted);
    if(state.style==0){text(48,compact?228:295,compact?156:176,value);text(50+textWidth(compact?156:176,value),compact?228:295,22,(n.second<10?":0":":")+std::to_string(n.second),p.muted);}
    else if(state.style==1){float scale=compact?1.45f:2.f;int x=compact?52:44,y=compact?113:117,step=compact?93:108;digitalDigit(x,y,h/10,scale);digitalDigit(x+step,y,h%10,scale);int colon=x+step*2+4;vita2d_draw_fill_circle(colon,y+25*scale,3,p.accent);vita2d_draw_fill_circle(colon,y+60*scale,3,p.accent);int minutes=colon+22;digitalDigit(minutes,y,n.minute/10,scale);digitalDigit(minutes+step,y,n.minute%10,scale);float secondsScale=compact?.52f:.48f;int secondsX=minutes+step+49*scale+14,secondsY=y+93*scale-93*secondsScale;vita2d_draw_fill_circle(secondsX-7,secondsY+25*secondsScale,2,p.accent);vita2d_draw_fill_circle(secondsX-7,secondsY+60*secondsScale,2,p.accent);digitalDigit(secondsX,secondsY,n.second/10,secondsScale);digitalDigit(secondsX+31,secondsY,n.second%10,secondsScale);}
    else{const float cx=compact?156:182,cy=compact?178:230,r=compact?88:136,pi=3.14159265f;vita2d_draw_fill_circle(cx,cy,r+2,p.line);vita2d_draw_fill_circle(cx,cy,r,p.card);for(int i=0;i<60;++i){float a=i*pi/30,q=i%5==0?r-11:r-5;vita2d_draw_line(cx+sin(a)*q,cy-cos(a)*q,cx+sin(a)*(r-3),cy-cos(a)*(r-3),i%5==0?p.ink:p.line);}float ah=(n.hour%12+n.minute/60.f)*pi/6,am=(n.minute+n.second/60.f)*pi/30,as=n.second*pi/30;vita2d_draw_line(cx,cy,cx+sin(ah)*r*.54f,cy-cos(ah)*r*.54f,p.ink);vita2d_draw_line(cx,cy,cx+sin(am)*r*.81f,cy-cos(am)*r*.81f,p.ink);vita2d_draw_line(cx,cy,cx+sin(as)*r*.85f,cy-cos(as)*r*.85f,p.accent);vita2d_draw_fill_circle(cx,cy,3,p.accent);}
    if(state.style==1)clockWeather(compact?444:498,compact?117:149,compact?112:66,true);else if(state.style==0)clockWeather(compact?490:498,compact?130:185,66,true);else clockWeather(compact?268:332,compact?244:276,compact?284:222,false);
    if(!state.time24)text(state.style==2?332:528,state.style==2?(compact?192:260):state.style==1?(compact?247:327):(compact?218:273),state.style==2?16:12,n.hour<12?"AM":"PM",p.accent);auto marks=marksFor(state,d);auto hs=holidayItems(state,d);std::string event=!marks.empty()&&!marks[0].second.title.empty()?marks[0].second.title:!hs.empty()?holidayTitle(hs[0]):"";
    if(state.style==2){wrap(compact?268:332,compact?161:180,18,dateWords(d)+" · "+weekName(weekday(d)),compact?284:222,2,p.muted);wrap(compact?268:332,compact?217:245,17,event,compact?284:222,2,p.accent);}else if(state.style==1&&compact){fit(260,104,15,dateWords(d)+" · "+weekName(weekday(d)),292,p.muted);fit(52,268,17,event,498,p.accent);}else{fit(52,compact?250:353,18,dateWords(d)+" · "+weekName(weekday(d)),498,p.muted);fit(52,compact?269:373,17,event,498,p.accent);}
    for(size_t i=clockScroll;i<clocks.size()&&i<(size_t)clockScroll+8;++i){int slot=i-clockScroll,x=48+(slot%4)*129,y=270+(slot/4)*51;const auto& c=clocks[i];if((int)i==homeClockFocus)outline(x-3,y,125,49,p.accent,1);fit(x+2,y+14,13,countryCity(c),state.time24?119:94,p.muted);for(const auto& place:state.regions)if(countryPlace(c,place.location)&&place.weather.valid){weatherIcon(x+63,y+26,place.weather.code,6);fit(x+77,y+32,12,valueIn(place.weather.temperature,0,state.units),44,metricColor(0));if(state.dualUnits)fit(x+77,y+46,10,valueIn(place.weather.temperature,0,1-state.units),44,p.muted);break;}if(zoneFor(c).empty())text(x+2,y+32,17,"—",p.muted);else{auto time=countryClock(c);fit(x+2,y+32,17,clockTime(time.hour,time.minute,state.time24,false),51,colors[c.color]);if(!state.time24)fit(x+97,y+14,9,time.hour<12?"AM":"PM",25,p.muted);fit(x+2,y+46,state.dualUnits?10:11,shortDate({time.year,time.month,time.day}),state.dualUnits?73:119,p.muted);}}
}
static unsigned personalDateColor(){return state.userRgb<0?colors[state.userColor]:0xff000000u|state.userRgb;}
static void holidayDots(Date date,int x,int y,int spacing=6,int perRow=10,bool alignRight=false){auto hs=calendarObservances(date);std::vector<unsigned> palette;for(const auto& h:hs){unsigned c=h.country=="USR"?personalDateColor():colors[countryColor(state,h.country)];if(std::find(palette.begin(),palette.end(),c)==palette.end())palette.push_back(c);}for(size_t i=0;i<palette.size()&&i<(size_t)perRow;++i)vita2d_draw_fill_circle(x+(alignRight?-1:1)*(int)(i%perRow)*spacing,y+(i/perRow)*6,2.5f,palette[i]);}
static void miniCalendar(){
    rect(598,82,334,296,p.card);fit(620,115,22,std::string(monthName(selected.m))+" "+std::to_string(selected.y),265);text(902,114,18,">",p.accent);
    for(int i=0;i<7;++i)text(621+i*43,142,14,weekName(i),i>=5?p.accent:p.muted);
    int start=weekday({selected.y,selected.m,1});Date current=today();for(int day=1;day<=days(selected.y,selected.m);++day){int index=start+day-1,x=617+(index%7)*43,y=151+(index/7)*31;Date date{selected.y,selected.m,day};auto marks=marksFor(state,date);int color=marks.empty()?0:marks[0].second.color;if(color)rect(x,y,38,28,colors[color]);unsigned ink=color?RGBA8(12,25,36,255):p.ink;text(x+6,y+20,18,std::to_string(day),ink);if(key(date)==key(current))outline(x-2,y-2,42,32,p.accent,2);holidayDots(date,x+34,y+3,6,5,true);if(homeCalendar&&day==selected.d)outline(x,y,38,28,p.ink,1);}
    static std::string signature,title;static int distance=-1;std::string currentSignature=key(today())+"/"+std::to_string(state.revision)+"/"+std::to_string(state.updated)+"/"+std::to_string(state.language);if(signature!=currentSignature){signature=currentSignature;Date next=today();title.clear();distance=-1;for(int n=0;n<=370;++n){auto list=calendarObservances(next);if(!list.empty()){title=holidayTitle(list.front());distance=n;break;}next=shift(next,1);}}if(distance>=0){std::string label=distance==0?t("Сегодня","Today"):t("Через ","In ")+std::to_string(distance)+t(" дн."," days");wrap(615,351,13,label+" · "+title,301,2,p.accent);}else fit(615,357,13,t("Ближайший праздник не загружен","Next holiday is not loaded"),301,p.muted);
}
static void home(){weatherRegion=-1;homeClockFocus=homeBlock<0&&homeFocus>=1&&homeFocus<=16?homeFocus-1:-1;homeCalendar=homeBlock<0&&homeFocus>=101&&homeFocus<=131;if(homeCalendar)selected.d=std::clamp(homeFocus-100,1,days(selected.y,selected.m));if(homeFocus>=200&&homeFocus<210)forecastFocus=homeFocus-200;
    clockFace();if(homeBlock==0)outline(28,82,550,296,p.accent,2);miniCalendar();if(homeBlock==1)outline(598,82,334,296,p.accent,2);if(homeBlock==2)outline(18,407,934,113,p.accent,2);if(homeFocus==300)outline(614,92,302,31,p.accent,1);fit(28,400,17,cityName(state.location)+" · "+t("10 дней","10 days"),trackedClocks().size()>8?440:820,p.muted);if(trackedClocks().size()>8){text(483,400,17,"‹",clockScroll?p.accent:p.muted);fit(504,399,12,std::to_string(clockScroll/8+1)+" / "+std::to_string((trackedClocks().size()+7)/8),42,p.muted);text(555,400,17,"›",clockScroll+8<(int)trackedClocks().size()?p.accent:p.muted);if(homeFocus==80)outline(476,379,24,25,p.accent,1);if(homeFocus==81)outline(548,379,25,25,p.accent,1);}
    for(int i=0;i<10;++i){int x=20+i*93;bool present=viewWeather().valid&&i<(int)viewWeather().dates.size();card(x,409,87,109);Date d=present?parseDate(viewWeather().dates[i]):shift(today(),i);if(homeBlock<0&&homeFocus==200+i){rect(x+8,409,71,3,p.accent);}if(key(d)==key(today()))outline(x,409,87,109,p.accent,2);fit(x+8,433,15,std::string(weekName(weekday(d)))+" "+std::to_string(d.d),73);
        if(present){bool windy=number(daily(),"wind_speed_10m_max",i,0)>=30;weatherIcon(x+(windy?28:43),454,(int)number(daily(),"weather_code",i,viewWeather().code),6);if(windy)drawAssetIcon(x+60,454,3,24,metricColor(3));fit(x+5,489,15,temp(viewWeather().lows[i]),38,p.muted);fit(x+46,489,15,temp(viewWeather().highs[i]),36,metricColor(0));if(state.dualUnits)fit(x+7,509,12,numeric(temperature(viewWeather().lows[i],1-state.units))+" / "+numeric(temperature(viewWeather().highs[i],1-state.units))+(state.units?"°C":"°F"),76,p.muted);else fit(x+7,509,12,numeric(number(daily(),"precipitation_probability_max",i))+"%",76,metricColor(1));}else text(x+10,487,17,"—",p.muted);
    }
}
static void openWeather(int index){if(!viewWeather().valid||index<0||index>=(int)viewWeather().dates.size()){notice=t("Прогноз ещё не загружен","Forecast has not loaded yet");return;}weatherDay=index;forecastFocus=index;graphHour=12;notice.clear();}
static const char* metricName(int m){const char* names[]={t("Температура","Temperature"),t("Осадки","Precipitation"),t("Влажность","Humidity"),t("Ветер","Wind"),t("Давление","Pressure"),t("Облака","Clouds")};return names[m%6];}
static const char* metricField(int m){static const char* fields[]={"temperature_2m","precipitation","relative_humidity_2m","wind_speed_10m","pressure_msl","cloud_cover"};return fields[m%6];}
static void weatherDetails(){
    if(weatherDay>=(int)viewWeather().dates.size()){weatherDay=-1;home();return;}auto hours=hoursForDay(weatherDay);graphHour=std::clamp(graphHour,0,std::max(0,(int)hours.size()-1));Date date=parseDate(viewWeather().dates[weatherDay]);weatherIcon(37,88,(int)number(daily(),"weather_code",weatherDay,viewWeather().code),9);static const char* ru[]={"Понедельник","Вторник","Среда","Четверг","Пятница","Суббота","Воскресенье"};static const char* en[]={"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"};fit(63,88,20,std::string(state.language?en[weekday(date)]:ru[weekday(date)])+", "+std::to_string(date.d)+" "+dateMonth(date.m),342);fit(63,110,14,cityName(viewLocation()),342,p.muted);
    for(int i=0;i<(int)viewWeather().dates.size()&&i<10;++i){int x=426+i*51;Date day=parseDate(viewWeather().dates[i]);if(key(day)==key(forecastToday()))outline(x,68,47,47,p.accent,1);if(i==weatherDay)rect(x+4,112,39,2,p.accent);fit(x+4,79,11,weekName(weekday(day)),39,p.muted);weatherIcon(x+23,91,(int)number(daily(),"weather_code",i,viewWeather().code),6);text(x+4,111,12,std::to_string(day.d));}
    for(int m=0;m<6;++m){int x=20+m*155;card(x,120,145,42);infoIcon(x+17,141,m,metricColor(m));fit(x+33,148,15,metricName(m),105,m==graphMetric?metricColor(m):p.muted);if(m==graphMetric)rect(x+10,159,125,2,metricColor(m));}
    card(20,174,610,221);card(644,174,296,221);unsigned c=metricColor(graphMetric);double min=1e9,max=-1e9;for(int index:hours){double v=number(hourly(),metricField(graphMetric),index);if(std::isfinite(v)){min=std::min(min,v);max=std::max(max,v);}}if(max<min){min=0;max=1;}if(graphMetric==1||graphMetric==2||graphMetric==5)min=0;if(graphMetric==2||graphMetric==5)max=100;if(max-min<1)max=min+1;
    text(40,202,17,metricName(graphMetric),c);fit(40,229,13,valueIn(max,graphMetric,state.units),125,p.muted);fit(40,365,13,valueIn(min,graphMetric,state.units),125,p.muted);
    const float left=136,right=607,top=218,bottom=358;for(int row=0;row<4;++row)rect(left,top+row*(bottom-top)/3,right-left,1,p.line);
    float prevX=0,prevY=0;bool hasPrevious=false;for(size_t i=0;i<hours.size();++i){double v=number(hourly(),metricField(graphMetric),hours[i]);float x=left+(right-left)*i/std::max(1,(int)hours.size()-1);if(!std::isfinite(v)){hasPrevious=false;continue;}float y=bottom-(v-min)/(max-min)*(bottom-top);if(graphMetric==1)rect(x-3,y,6,bottom-y,c);else if(hasPrevious){for(int a=0;a<2;++a)vita2d_draw_line(prevX,prevY+a,x,y+a,c);}if((int)i==graphHour){rect(x,top,1,bottom-top,p.accent);vita2d_draw_fill_circle(x,y,5,c);}prevX=x;prevY=y;hasPrevious=true;}
    for(int i=0;i<4;++i){int pos=hours.empty()?0:i*((int)hours.size()-1)/3;if(!hours.empty())fit(left+i*(right-left)/3-10,382,12,(pos==(int)hours.size()-1&&stringAt(hourly(),"time",hours[pos]).substr(0,10)!=viewWeather().dates[weatherDay]?"24:00":stampTime(stringAt(hourly(),"time",hours[pos]))),85,p.muted);}
    text(664,201,17,t("Сводка дня","Daily summary"));fit(664,228,20,temp(viewWeather().lows[weatherDay])+" / "+temp(viewWeather().highs[weatherDay]),255,metricColor(0));if(state.dualUnits)fit(664,247,12,valueIn(viewWeather().lows[weatherDay],0,1-state.units)+" / "+valueIn(viewWeather().highs[weatherDay],0,1-state.units),255,p.muted);
    fit(664,269,15,t("Восход","Sunrise")+std::string(" ")+stampTime(stringAt(daily(),"sunrise",weatherDay))+" · "+stampTime(stringAt(daily(),"sunset",weatherDay)),257,p.muted);fit(664,293,15,t("УФ ","UV ")+numeric(number(daily(),"uv_index_max",weatherDay),1)+" · "+t("Осадки ","Precip. ")+rain(number(daily(),"precipitation_sum",weatherDay)),257,metricColor(1));
    text(664,319,14,t("Ожидаемый дождь","Expected rain"),metricColor(1));std::string summary;for(const auto& interval:rainIntervals(viewWeather(),viewWeather().dates[weatherDay])){if(!summary.empty())summary+=" · ";summary+=clockTime(interval.first%24,0,state.time24)+"–"+clockTime(interval.second%24,0,state.time24);}wrap(664,343,14,hours.empty()?"—":summary.empty()?t("Не ожидается","Not expected"):summary,250,2,p.muted);
    card(20,407,920,111);int index=hours.empty()?-1:hours[graphHour];fit(40,433,17,index<0?"—":stringAt(hourly(),"time",index).substr(0,10)!=viewWeather().dates[weatherDay]?t("24:00 · +1 день","24:00 · +1 day"):stampTime(stringAt(hourly(),"time",index)),190,p.accent);for(int m=0;m<6;++m){int x=36+m*151;infoIcon(x+11,454,m,metricColor(m));fit(x+28,459,13,metricName(m),119,p.muted);dualValue(x+3,485,number(hourly(),metricField(m),index<0?300:index),m,17,142);}if(index>=0){fit(237,433,13,t("Ощущается ","Feels ")+temp(number(hourly(),"apparent_temperature",index))+" · "+t("Шанс ","Chance ")+numeric(number(hourly(),"precipitation_probability",index))+"% · "+t("Порывы ","Gusts ")+wind(number(hourly(),"wind_gusts_10m",index)),680,p.muted);}
}
static void calendar(){
    rect(28,82,636,409,p.card);text(50,121,28,std::string(monthName(selected.m))+" "+std::to_string(selected.y));
    for(int i=0;i<7;++i)text(65+i*86,157,16,weekName(i),i>=5?p.accent:p.muted);
    int start=weekday({selected.y,selected.m,1});Date current=today();
    for(int day=1;day<=days(selected.y,selected.m);++day){int index=start+day-1,x=49+(index%7)*86,y=173+(index/7)*49;Date date{selected.y,selected.m,day};auto marks=marksFor(state,date);int c=marks.empty()?0:marks[0].second.color;if(day==selected.d)outline(x-3,y-3,79,45,p.ink,1);rect(x,y,73,39,c?colors[c]:p.card);unsigned ink=c?RGBA8(12,25,36,255):p.ink;text(x+12,y+28,22,std::to_string(day),ink);if(key(date)==key(current))outline(x+1,y+1,71,37,p.accent,2);holidayDots(date,x+68,y+5,6,10,true);if(!marks.empty()&&!marks[0].second.title.empty())rect(x+57,y+23,8,3,ink);}
    rect(684,82,248,409,p.card);fit(702,120,20,dateWords(selected),208);auto marks=marksFor(state,selected);auto hs=holidayItems(state,selected);
    if(!marks.empty()){vita2d_draw_fill_circle(706,209,3,state.userRgb<0?colors[state.userColor]:0xff000000u|state.userRgb);text(718,214,13,t("Своя дата","Personal date"),p.muted);}if(marks.empty())wrap(702,152,18,t("Добавить событие","Add event"),208,2,p.muted);else{wrap(702,152,20,marks[0].second.title.empty()?t("Цветная отметка","Color mark"):marks[0].second.title,208,2);}
    holidayScroll=std::max(0,std::min(holidayScroll,std::max(0,(int)hs.size()-3)));for(int i=0;i<3&&holidayScroll+i<(int)hs.size();++i){const auto& h=hs[holidayScroll+i];vita2d_draw_fill_circle(706,237+i*54,3,colors[countryColor(state,h.country)]);fit(717,242+i*54,14,h.country+" · "+t("праздник","observance"),192);wrap(702,263+i*54,14,holidayTitle(h),208,2,p.muted);}
    if(hs.empty())wrap(702,256,16,marks.empty()?t("Праздников на этот день нет в загруженных списках","No observances in loaded calendars for this day"):t("Других праздников нет в загруженных списках","No other observances in loaded calendars"),208,4,p.muted);
    if(!marks.empty()&&!marks[0].second.title.empty())fit(702,464,14,std::string(t("Повтор: ","Repeat: "))+(marks[0].second.yearly?t("Каждый год","Every year"):t("Нет","None")),208,p.ink);
}
static std::vector<Country> filteredCountries(){std::vector<Country> out;for(const auto& c:catalog())if(matchesCountry(countrySearch,c.code,c.name,countryName(c)+" "+localizedCountries.value(c.code,std::string{})))out.push_back(c);return out;}
static void openCountry(const Country& option){countryReturnPage=page;auto it=std::find_if(state.countries.begin(),state.countries.end(),[&](const Country& c){return c.code==option.code;});if(it==state.countries.end()){if(state.countries.size()>=8){notice=t("Можно выбрать до 8 стран","You can select up to 8 countries");return;}Country c=option;bool used[11]{};used[state.localColor]=used[state.internationalColor]=true;for(const auto& item:state.countries)used[item.color]=true;c.color=1;while(c.color<10&&used[c.color])++c.color;c.cityEnabled=false;c.clock=true;c.zone="";c.clockCity.clear();c.cityPinned=false;state.countries.push_back(c);countryEdit=state.countries.size()-1;persist();updateNetwork();}else countryEdit=it-state.countries.begin();settingsTab=5;settingsRow=settingsScroll=0;page=2;notice.clear();}
static void countryToggle(int index){auto options=filteredCountries();if(index>=0&&index<(int)options.size())openCountry(options[index]);}

static int& colorRGB(){if(colorTarget==5)return state.userRgb;if(colorTarget==2)return state.textRgb;if(colorTarget==3)return state.accentRgb;return colorTarget==4?state.nightLook.bgRgb:state.dayLook.bgRgb;}
static int& holidayColor(){if(colorTarget==10)return state.localColor;if(colorTarget==11)return state.internationalColor;if(colorTarget==13)return state.userColor;return state.countries[countryEdit].color;}
static void openColor(int target){colorReturnTab=settingsTab;colorReturnRow=settingsRow;colorTarget=target;paletteFocus=0;settingsTab=7;settingsRow=0;}
static void closeColor(){settingsTab=colorReturnTab;settingsRow=colorReturnRow;settingsScroll=0;}
static const int swatches[]={0x2d2c1c,0xf7f2eb,0x000000,0xffffff,0x706050,0xbdb397,0x707d19,0xc1de5a,0xeda34d,0xed8356,0xcf4d55,0xdf7777,0x459fea,0x4f82eb,0x52bdd8,0x48c2eb,0xcaaf50,0x7fb94b,0x67c9b6,0x9bc59c,0x916bc5,0xb982dd,0xa16fcf,0x779fed};
static int paletteDefault(){if(colorTarget==5)return 0xe077bb;return colorTarget==2?(currentLook().theme?0xf7f2eb:0x2d2c1c):colorTarget==3?(currentLook().theme?0xc1de5a:0x707d19):colorTarget==4?0x1e160d:0xe8eff0;}
static void applyDefaultColor(){if(colorTarget==2)state.textRgb=-1;else if(colorTarget==3)state.accentRgb=-1;else colorRGB()=paletteDefault();if(colorTarget==0)state.dayLook.background=0;if(colorTarget==4)state.nightLook.background=0;persist();closeColor();}
static std::vector<int> countryCityPlaces(){std::vector<int> out;if(countryEdit<0||countryEdit>=(int)state.countries.size())return out;const auto& c=state.countries[countryEdit];for(int i=0;i<(int)state.regions.size();++i)if(countryPlace(c,state.regions[i].location)||(state.regions[i].origin==3&&state.regions[i].location.country==c.code))out.push_back(i);return out;}
static int settingsSection(){if(settingsTab<=2)return settingsTab;if(settingsTab==13)return 1;if(settingsTab==7||settingsTab==9)return colorReturnTab==1?1:colorReturnTab==5||colorReturnTab==2?2:0;return settingsTab==6?0:2;}
static void selectSettingsSection(int section){settingsTab=std::clamp(section,0,2);settingsRow=settingsScroll=0;countryReturnPage=2;countryEdit=cityEdit=-1;cityTarget=-1;notice.clear();}
static int settingCount(){if(settingsTab==11)return countryCityPlaces().size()+1;if(settingsTab==12||settingsTab==14)return 4;if(settingsTab==0)return state.themeMode==2?9:6;if(settingsTab==1)return 8;if(settingsTab==2)return 4+state.countries.size();if(settingsTab==3)return usesPostal(state.location.country)?4:3;if(settingsTab==5)return 6;if(settingsTab==6)return 11+backgroundFiles.size();if(settingsTab==7)return colorTarget>=10?10:74+(int)state.recentColors.size();if(settingsTab==9)return 6;if(settingsTab==10)return zonesFor(state.countries[countryEdit].code).size();if(settingsTab==8)return cityResults.size();return filteredCountries().size();}
static std::string enabled(bool v){return v?t("Вкл.","On"):t("Выкл.","Off");}
static std::string backgroundName(int id){const char* names[]={t("Цвет","Color"),t("Лес","Forest"),t("Горы","Mountains"),t("Сиэтл","Seattle"),t("Нью-Йорк","New York"),t("Своё изображение","Custom image"),t("Море и лес","Sea and forest"),t("Снежные вершины","Snowy peaks"),t("Городская улица","City street"),t("Канал","Canal"),t("Париж","Paris"),t("Фьорд","Fjord")};return names[std::clamp(id,0,11)];}
static int countryCityCount(const Country& c){int count=0;bool root=false;for(const auto& place:state.regions)if(countryPlace(c,place.location)||(place.origin==3&&place.location.country==c.code)){++count;root|=countryPlace(c,place.location);}return count+(c.cityEnabled&&!root?1:0);}
static std::string trackingName(const Country& c){return t("Праздники: ","Holidays: ")+enabled(c.holidays)+t(" · Города: "," · Cities: ")+std::to_string(countryCityCount(c));}
static std::string cityCapacity(){return t("Всего дополнительных городов: ","Additional cities in total: ")+std::to_string(trackedCityCount(state))+t(" из 16"," of 16");}
static std::string zoneLabel(const Location& l){int offset=zoneOffset(zoneRules(),l.zone,utcNow(),l.offset),minutes=std::abs(offset)/60;char value[24];snprintf(value,sizeof(value),"UTC%c%02d:%02d",offset<0?'-':'+',minutes/60,minutes%60);return std::string(value)+" · "+l.zone;}
static void toggleCityClock(){auto& c=state.countries[countryEdit];auto& city=state.regions[cityEdit];bool was=c.clock&&city.clock;if(!c.clock){for(int i:countryCityPlaces())state.regions[i].clock=false;c.clock=true;}city.clock=!was;persist();}
static void openClockCity(const Country& clock){openCountry(clock);for(int i:countryCityPlaces())if(countryPlace(clock,state.regions[i].location)){cityEdit=i;settingsTab=12;break;}}
static void settingLine(int row,int y,const std::string& label,const std::string& value,int icon=-1,unsigned swatch=0,unsigned labelColor=0){card(44,y,872,52);if(row==settingsRow)rect(44,y+4,3,44,p.accent);int x=62;if(icon>=0){infoIcon(74,y+26,icon,swatch?swatch:p.accent);x=98;}if(value.empty())fit(x,y+32,18,label,740,labelColor?labelColor:p.ink);else{fit(x,y+22,16,label,740,labelColor?labelColor:p.muted);fit(x,y+44,19,value,740);}if(swatch){rect(851,y+10,42,32,swatch);outline(851,y+10,42,32,p.line,1);}}

static void openCitySearch(int target){page=2;cityTarget=target;cityResults=Json::array();citySearch.clear();cityFocus=-1;cityScroll=0;settingsTab=8;settingsRow=0;keyboard(2,"",t("Поиск города","Search cities"));}
static void setWeatherFocus(const Location& l);
static void chooseCity(int index){if(index<0||index>=(int)cityResults.size())return;Location l=decodeLocation(cityResults[index].at("location"));if(cityTarget==-2){auto it=std::find_if(state.regions.begin(),state.regions.end(),[&](const WeatherPlace& p){return sameCity(p.location,l);});if(it==state.regions.end()){if(trackedCityCount(state)>=16){notice=t("Общий лимит: 16 дополнительных городов","Global limit: 16 additional cities");return;}state.regions.push_back({l,{ },0,2});weatherPlaceFocus=state.regions.size();}else{it->origin=std::max(it->origin,2);weatherPlaceFocus=1+(it-state.regions.begin());}setWeatherFocus(l);page=3;settingsTab=0;weatherDay=-1;updateNetwork();}else if(cityTarget>=0&&cityTarget<(int)state.countries.size()){if(!addCountryCity(state,cityTarget,l)){notice=t("Общий лимит: 16 дополнительных городов","Global limit: 16 additional cities");return;}updateNetwork();settingsTab=11;settingsRow=0;}else{state.location=l;state.weather=Weather{};state.holidayYear=0;selected=today();settingsTab=3;settingsRow=1;updateNetwork();}persist();settingsScroll=0;}
static void applyPicker(){} // HSV is a draft until explicit confirmation.
static double analogAxis(int value){double v=(value-128)/127.;return std::abs(v)<.15?0:std::copysign((std::abs(v)-.15)/.85,v);}
static void pickerAnalog(int lx,int ly,int rx,int ry,double dt){dt=std::clamp(dt,0.,.05);picker.s=std::clamp(picker.s+analogAxis(lx)*dt*.65,0.,1.);picker.v=std::clamp(picker.v-analogAxis(ly)*dt*.65,0.,1.);double hue=std::abs(ry-128)>=std::abs(rx-128)?analogAxis(ry):analogAxis(rx);picker.h=fmod(picker.h+hue*dt*150.+360.,360.);}
static void selectedSwatch(int x,int y,int w,int h,bool chosen){if(!chosen)return;outline(x+2,y+2,w-4,h-4,0xff000000u,2);outline(x+4,y+4,w-8,h-8,0xffffffffu,2);vita2d_draw_fill_circle(x+w/2,y+h/2,5,0xff000000u);vita2d_draw_fill_circle(x+w/2,y+h/2,3,0xffffffffu);}
static void drawColorPicker(){drawPickerField(picker.h);for(int y=0;y<300;++y)rect(363,142+y,26,1,0xff000000u|hsvRgb({y*360./300,1,1}));outline(44+(int)(picker.s*294)-3,142+(int)((1-picker.v)*294)-3,7,7,0xffffffffu,2);rect(360,142+picker.h*299/360,32,3,p.ink);if(settingsRow==0)outline(360,139,32,306,p.accent,2);if(settingsRow==1)outline(41,139,306,306,p.accent,2);text(44,473,16,t("Цветовой тон","Hue"),p.muted);rect(363,458,68,42,0xff000000u|hsvRgb(picker));int rgb=hsvRgb(picker);const char* names[]={t("Красный (R)","Red (R)"),t("Зелёный (G)","Green (G)"),t("Синий (B)","Blue (B)")};for(int i=0;i<3;++i){int y=151+i*87,value=(rgb>>(i*8))&255;card(458,y,458,75);text(474,y+26,18,names[i],settingsRow==i+2?p.accent:p.muted);text(856,y+26,18,std::to_string(value));rect(476,y+51,408,4,p.line);rect(476,y+51,value*408/255,4,0xff000000u|(255<<(i*8)));vita2d_draw_fill_circle(476+value*408/255,y+53,5,p.ink);}button(458,425,458,t("Применить цвет","Apply color"),settingsRow==5);}
static void settings(){
    if(settingsTab==13){drawCalendarText(t("Статус загрузки","Download status"));return;}
    int active=settingsSection();
    const char* tabs[]={t("Оформление","Appearance"),t("Общие","General"),t("Локации","Locations")};for(int i=0;i<3;++i)button(20+i*310,78,300,tabs[i],active==i);
    if(settingsTab==10){auto zones=zonesFor(state.countries[countryEdit].code);if(zoneFocus<zoneScroll)zoneScroll=zoneFocus;if(zoneFocus>=zoneScroll+6)zoneScroll=zoneFocus-5;for(int n=0;n<6&&zoneScroll+n<(int)zones.size();++n){int i=zoneScroll+n,y=132+n*62;int saved=settingsRow;settingsRow=zoneFocus;Location l;l.zone=zones[i];settingLine(i,y,cityName(l),zones[i],6);settingsRow=saved;if(i==zoneFocus)outline(44,y,872,52,p.accent,1);}return;}
    if(settingsTab==8){text(44,524,11,"GeoNames · © OpenStreetMap contributors",p.muted);button(44,132,872,t("Поиск города: ","Search cities: ")+citySearch,cityFocus<0);if(cityFocus<cityScroll&&cityFocus>=0)cityScroll=cityFocus;if(cityFocus>=cityScroll+5)cityScroll=cityFocus-4;for(int n=0;n<5&&cityScroll+n<(int)cityResults.size();++n){int index=cityScroll+n,y=187+n*62;auto l=decodeLocation(cityResults[index].at("location"));card(44,y,872,55);if(index==cityFocus)outline(44,y,872,55,p.accent,1);fit(62,y+23,19,cityName(l)+" · "+countryName({l.country,l.country,1}),800);fit(62,y+46,14,(l.region.empty()?cityResults[index].value("region",std::string{}):regionName(l.country,l.region,state.language))+(l.postal.empty()?"":" · "+l.postal)+" · "+l.zone,800,p.muted);}return;}
    if(settingsTab==7){bool holiday=colorTarget>=10;if(holiday){for(int i=0;i<10;++i){int x=44+(i%6)*147,y=140+(i/6)*77;rect(x,y,62,62,colors[i+1]);selectedSwatch(x,y,62,62,holidayColor()==i+1);if(i==paletteFocus)outline(x-3,y-3,68,68,p.accent,2);}return;}text(44,144,15,t("По умолчанию","Default"),p.muted);rect(44,153,44,32,0xff000000u|paletteDefault());selectedSwatch(44,153,44,32,colorRGB()<0||colorRGB()==paletteDefault());if(paletteFocus==0)outline(41,150,50,38,p.accent,2);text(170,144,15,t("Недавние","Recent"),p.muted);int recent=state.recentColors.size();for(int i=0;i<recent;++i){int x=170+i*60;rect(x,153,44,32,0xff000000u|state.recentColors[i]);selectedSwatch(x,153,44,32,colorRGB()==state.recentColors[i]);if(paletteFocus==i+1)outline(x-3,150,50,38,p.accent,2);}for(int i=0;i<72;++i){int x=44+(i%12)*73,y=202+(i/12)*43;rect(x,y,35,35,0xff000000u|presetRgb(i));selectedSwatch(x,y,35,35,colorRGB()==presetRgb(i));if(paletteFocus==recent+1+i)outline(x-3,y-3,41,41,p.accent,2);}card(44,466,872,42);text(60,494,18,t("Свой цвет · цветовое поле и RGB","Custom color · color field and RGB"));if(paletteFocus==recent+73)outline(44,466,872,42,p.accent,2);return;}
    if(settingsTab==9){drawColorPicker();return;}
    if(settingsTab==4){button(44,132,872,t("Поиск: ","Search: ")+countrySearch,countryFocus<0);auto options=filteredCountries();countryFocus=std::clamp(countryFocus,-1,std::max(-1,(int)options.size()-1));if(countryFocus>=0){if(countryFocus<countryScroll)countryScroll=countryFocus;if(countryFocus>=countryScroll+6)countryScroll=countryFocus-5;}countryScroll=std::max(0,countryScroll);for(int row=0;row<6&&countryScroll+row<(int)options.size();++row){int index=countryScroll+row,y=182+row*54;const auto& c=options[index];auto it=std::find_if(state.countries.begin(),state.countries.end(),[&](const Country& v){return v.code==c.code;});card(44,y,872,49);if(index==countryFocus)rect(44,y+3,3,43,p.accent);fit(62,y+31,19,c.code+" · "+countryName(c),493);fit(570,y+31,15,it!=state.countries.end()?trackingName(*it):"+",321,it!=state.countries.end()?colors[it->color]:p.muted);}if(options.empty())text(62,222,21,t("Ничего не найдено","No results"),p.muted);return;}

    if(settingsTab==6){fileFocus=std::clamp(fileFocus,0,settingCount()-1);if(fileFocus<fileScroll)fileScroll=fileFocus/3*3;if(fileFocus>=fileScroll+6)fileScroll=(fileFocus/3-1)*3;for(int n=0;n<6&&fileScroll+n<settingCount();++n){int index=fileScroll+n,x=32+(n%3)*307,y=136+(n/3)*187;card(x,y,288,176);if(index==0){for(int c=0;c<6;++c)rect(x+12+c*44,y+13,44,126,0xff000000u|swatches[c+6]);drawAssetIcon(x+144,y+77,7,32,p.ink);}else drawGalleryImage(index,x+10,y+8,268,132);std::string name=index<11?backgroundName(galleryBackground(index)):backgroundFiles[index-11].substr(backgroundFiles[index-11].rfind('/')+1);fit(x+12,y+163,18,name,262);if(index==fileFocus)outline(x-2,y-2,292,180,p.accent,2);}return;}
    if(settingsTab==5)fit(44,524,14,t("Праздники — для страны. Время и погода — для каждого города.","Holidays belong to the country. Clocks and weather belong to each city."),872,p.muted);
    if(settingsTab==11)fit(44,524,14,countryName(state.countries[countryEdit])+t(" · Основная локация не входит в лимит 16 городов"," · Your main location is outside the 16-city limit"),872,p.muted);
    if(settingsTab==12)fit(44,524,14,t("Выключение часов не удаляет город из погоды","Turning off the clock keeps this city's weather"),872,p.muted);
    int count=settingCount();settingsRow=std::clamp(settingsRow,0,std::max(0,count-1));if(settingsRow<settingsScroll)settingsScroll=settingsRow;if(settingsRow>=settingsScroll+6)settingsScroll=settingsRow-5;
    for(int row=0;row<6&&settingsScroll+row<count;++row){int i=settingsScroll+row,y=132+row*62;std::string label,value;int icon=-1;unsigned swatch=0;
        if(settingsTab==0){switch(i){case 0:label=t("Тема","Theme");value=state.themeMode==0?t("Светлая","Light"):state.themeMode==1?t("Тёмная","Dark"):t("Автоматически","Automatic");break;case 1:label=t("Вид часов","Clock style");value=styleName(state.style);icon=6;break;case 2:label=t("Цвет текста","Text color");icon=7;swatch=state.textRgb>=0?0xff000000u|state.textRgb:p.ink;break;case 3:label=t("Основной цвет","Accent color");icon=7;swatch=state.accentRgb>=0?0xff000000u|state.accentRgb:p.accent;break;case 4:label=t("Прозрачность панелей","Panel transparency");value=std::to_string(100-state.dayLook.opacity)+"%";break;case 5:label=state.themeMode==2?t("Дневной фон","Day background"):t("Фон","Background");value=backgroundName(state.themeMode==1?state.nightLook.background:state.dayLook.background);icon=8;break;case 6:if(state.themeMode==2){label=t("Ночной фон","Night background");value=backgroundName(state.nightLook.background);icon=8;}break;case 7:label=t("Начало дня","Day begins");value=clockTime(state.dayStart,0,state.time24);break;case 8:label=t("Начало ночи","Night begins");value=clockTime(state.nightStart,0,state.time24);break;}}
        else if(settingsTab==1){if(i==0){label=t("Язык","Language");value=state.language?"English":"Русский";}if(i==1){label=t("Формат времени","Time format");value=state.time24?"24h":"12h";}if(i==2){label=t("Основные единицы","Primary units");value=state.units?t("Американские","US customary"):t("Метрические","Metric");}if(i==3){label=t("Вторая система меньшим размером","Secondary units in small text");value=enabled(state.dualUnits);}if(i==4){label=t("Подсказки управления","Control hints");value=enabled(state.hints);}if(i==5){label=t("Экран всегда включён","Keep screen awake");value=enabled(state.keepScreen);}if(i==6){label=t("Цвет своих дат","Personal date color");icon=15;swatch=personalDateColor();}if(i==7){label=t("Статус загрузки погоды и праздников","Weather and holiday download status");value=t("Подробности последнего обновления","Details of the last update");icon=5;}}
        else if(settingsTab==2){if(i==0){label=t("Место для погоды и календаря","Weather and calendar location");value=cityName(state.location)+" · "+state.location.country;}else if(i==1){label=t("Праздники текущей страны","Current country holidays");value=state.location.country+" · "+enabled(state.followLocal);icon=15;swatch=colors[state.localColor];}else if(i==2){label=t("Международные даты","International dates");value=enabled(state.international);icon=15;swatch=colors[state.internationalColor];}else if(i==3){label=t("Добавить страну / поиск","Add country / search");value="+";}else{const auto& c=state.countries[i-4];label=c.code+" · "+countryName(c);value=trackingName(c);icon=6;swatch=colors[c.color];}}
        else if(settingsTab==3){if(i==0){label=t("Определить по IP","Locate by IP");value=cityName(state.location)+" · "+state.location.country;}if(i==1){label=state.location.country=="US"?t("Город / ZIP-код","City / ZIP code"):usesPostal(state.location.country)?t("Город / индекс","City / postal code"):t("Выбрать город","Choose city");value=cityName(state.location);}if(i==2){label=regionLabel(state.location.country,state.language);value=regionName(state.location.country,state.location.region,state.language);if(value.empty())value=t("Выбрать","Choose");}if(i==3){label=postalLabel(state.location.country,state.language);value=state.location.postal.empty()?t("Поиск по индексу","Search by postal code"):state.location.postal;}}
        else if(settingsTab==11){auto places=countryCityPlaces();if(i==(int)places.size()){label=t("Добавить город / поиск","Add city / search");value=cityCapacity();}else{const auto& place=state.regions[places[i]];label=cityName(place.location);value=zoneLabel(place.location)+t(" · Часы: "," · Clock: ")+enabled(state.countries[countryEdit].clock&&place.clock);icon=6;}}
        else if(settingsTab==14){const auto& place=state.regions[cityEdit];if(i==0){label=cityName(place.location);value=zoneLabel(place.location);icon=6;}if(i==1){label=t("Регион","Region");value=place.location.region.empty()?countryName({place.location.country,place.location.country,1}):regionName(place.location.country,place.location.region,state.language);icon=15;}if(i==2){label=t("Удаление уберёт город из погоды и дополнительных часов","Removing this city removes its weather and extra clock");}if(i==3)label=t("Удалить город","Remove city");}
        else if(settingsTab==12){const auto& place=state.regions[cityEdit];if(i==0){label=cityName(place.location);value=zoneLabel(place.location);icon=6;}else if(i==1){label=t("Показывать часы этого города на главном экране","Show this city's clock on Home");value=enabled(state.countries[countryEdit].clock&&place.clock);icon=6;}else if(i==2){label=t("Праздники и цвет задаются для страны","Holidays and color belong to the country");value=countryName(state.countries[countryEdit]);icon=15;}else label=t("Удалить город","Remove city");}
        else if(settingsTab==5&&countryEdit>=0&&countryEdit<(int)state.countries.size()){const auto& c=state.countries[countryEdit];if(i==0){label=countryName(c)+t(" · Праздники страны"," · Country holidays");value=enabled(c.holidays);icon=15;}if(i==1){label=t("Цвет праздников этой страны","This country's holiday color");icon=7;swatch=colors[c.color];}if(i==2){label=t("Города · время и погода","Cities · clocks and weather");value=t("В этой стране: ","In this country: ")+std::to_string(countryCityCount(c))+" · "+cityCapacity();icon=6;}if(i==3)label=t("Удалить страну","Remove country");if(i==4){label=t("Добавить город / поиск","Add city / search");value=t("Часовой пояс определяется по городу","Time zone comes from the city");icon=6;}if(i==5){label=t("Добавить город из базового списка","Add city from the default list");value=t("Выбрать город, затем уточнить в поиске","Choose a city, then refine the search");icon=6;}}
        settingLine(i,y,label,value,icon,swatch,(settingsTab==5&&i==3)||((settingsTab==12||settingsTab==14)&&i==3)?colors[9]:0);
    }
}

static std::vector<int> eventRows(){auto marks=marksFor(state,selected);if(marks.empty())return {0,1};return marks[0].second.title.empty()?std::vector<int>{0,1,3}:std::vector<int>{0,1,2,3};}
static void moveEvent(int delta){auto rows=eventRows();auto it=std::find(rows.begin(),rows.end(),calendarAction);int index=it==rows.end()?0:it-rows.begin();calendarAction=rows[std::clamp(index+delta,0,(int)rows.size()-1)];}
static void eventSettings(){fit(44,108,24,dateWords(selected),850);auto marks=marksFor(state,selected);std::string title=marks.empty()?"":marks[0].second.title;bool yearly=!marks.empty()&&marks[0].second.yearly;const char* labels[]={t("Событие","Event"),t("Цвет дня","Day color"),t("Повтор","Repeat"),t("Удалить событие","Delete event")};auto rows=eventRows();if(std::find(rows.begin(),rows.end(),calendarAction)==rows.end())calendarAction=0;for(int row=0;row<(int)rows.size();++row){int i=rows[row],y=134+row*83;card(44,y,872,70);if(calendarAction==i)outline(44,y,872,70,p.accent,2);text(62,y+(i==3?42:25),17,labels[i],i==3?colors[9]:p.muted);if(i==0)fit(62,y+55,21,title.empty()?t("Добавить название","Add title"):title,820);if(i==1){int c=marks.empty()?0:marks[0].second.color;rect(62,y+38,44,23,c?colors[c]:p.line);}if(i==2)text(62,y+55,21,yearly?t("Каждый год","Every year"):t("Нет","None"));}}
static void eventAction(){if(calendarAction==0)edit();if(calendarAction==1)color();if(calendarAction==2)repeat();if(calendarAction==3)deleteMark();}
struct WeatherRow {Location location;int region=-1;};
static std::vector<WeatherRow> weatherRows(){std::vector<WeatherRow> out={{state.location,-1}};std::vector<int> used;for(const auto& c:state.countries){if(!c.cityEnabled)continue;std::string zone=zoneFor(c);int found=-1;for(int i=0;i<(int)state.regions.size();++i){const auto& l=state.regions[i].location;if(countryPlace(c,l)){found=i;break;}}if(found>=0){out.push_back({state.regions[found].location,found});used.push_back(found);}else{Location l;l.city=c.clockCity.empty()?zoneCity(zone):c.clockCity;if(l.city.empty())l.city=countryName(c);l.country=c.code;l.zone=zone;out.push_back({l,-100-(int)out.size()});}}for(int i=0;i<(int)state.regions.size();++i)if(state.regions[i].origin!=1&&std::find(used.begin(),used.end(),i)==used.end())out.push_back({state.regions[i].location,i});return out;}
static void setWeatherFocus(const Location& l){auto rows=weatherRows();for(int i=0;i<(int)rows.size();++i)if(sameCity(rows[i].location,l)){weatherPlaceFocus=i;weatherPlaceScroll=0;return;}}
static void weatherPlaces(){auto rows=weatherRows();int count=rows.size()+1;weatherPlaceFocus=std::clamp(weatherPlaceFocus,0,count-1);if(weatherPlaceFocus<weatherPlaceScroll)weatherPlaceScroll=weatherPlaceFocus;if(weatherPlaceFocus>=weatherPlaceScroll+6)weatherPlaceScroll=weatherPlaceFocus-5;for(int n=0;n<6&&weatherPlaceScroll+n<count;++n){int i=weatherPlaceScroll+n,y=92+n*68;card(28,y,904,60);if(i==weatherPlaceFocus)outline(28,y,904,60,p.accent,1);if(i==count-1){drawAssetIcon(56,y+30,15,24,p.accent);text(82,y+38,22,t("Поиск другого города","Search another city"));continue;}const auto& l=rows[i].location;Weather empty;const auto& w=rows[i].region==-1?state.weather:rows[i].region>=0?state.regions[rows[i].region].weather:empty;fit(48,y+25,20,cityName(l)+" · "+countryName({l.country,l.country,1}),535);fit(48,y+48,14,(rows[i].region==-1?t("Основная локация · ","Main location · "):l.region.empty()?"":regionName(l.country,l.region,state.language)+" · ")+l.zone,535,p.muted);if(rows[i].region>=0)for(int dot=0;dot<3;++dot)vita2d_draw_fill_circle(601+dot*7,y+30,2,p.accent);if(w.valid){weatherIcon(638,y+29,w.code,9);fit(668,y+25,21,valueIn(w.temperature,0,state.units),127,metricColor(0));if(state.dualUnits)fit(805,y+25,14,valueIn(w.temperature,0,1-state.units),110,p.muted);if(!w.lows.empty()&&!w.highs.empty()){fit(668,y+48,14,numeric(temperature(w.lows[0],state.units))+"° / "+numeric(temperature(w.highs[0],state.units))+(state.units?"°F":"°C"),127,p.muted);if(state.dualUnits)fit(805,y+48,11,numeric(temperature(w.lows[0],1-state.units))+"° / "+numeric(temperature(w.highs[0],1-state.units))+(state.units?"°C":"°F"),110,p.muted);}}else fit(660,y+36,16,networkLoading()?t("Загрузка…","Loading…"):t("Нет данных · повторить","No data · retry"),254,p.muted);}}
static void manageWeatherCity(){auto rows=weatherRows();if(weatherPlaceFocus<0||weatherPlaceFocus>=(int)rows.size())return;int index=rows[weatherPlaceFocus].region;if(index<0){notice=t("Основная локация меняется в настройках Локаций","Change the main location in Locations settings");return;}cityEdit=index;page=2;settingsTab=14;settingsRow=settingsScroll=0;countryReturnPage=2;}
static void chooseWeatherPlace(){auto rows=weatherRows();if(weatherPlaceFocus==(int)rows.size()){openCitySearch(-2);return;}if(weatherPlaceFocus<0||weatherPlaceFocus>=(int)rows.size())return;if(rows[weatherPlaceFocus].region<-1){notice=t("Прогноз ещё не загружен","Forecast has not loaded yet");updateNetwork();return;}weatherRegion=rows[weatherPlaceFocus].region;if(!viewWeather().valid){updateNetwork();return;}openWeather(0);}
static void settingsAction(int delta=1){
 if(settingsTab==7){if(colorTarget>=10)holidayColor()=paletteFocus+1;else if(paletteFocus==73+(int)state.recentColors.size()){picker=rgbHsv(colorRGB()<0?paletteDefault():colorRGB());settingsTab=9;settingsRow=0;return;}else if(paletteFocus==0){applyDefaultColor();return;}else{int recent=state.recentColors.size();colorRGB()=paletteFocus<=recent?state.recentColors[paletteFocus-1]:presetRgb(paletteFocus-recent-1);rememberColor(state,colorRGB());if(colorTarget==0)state.dayLook.background=0;if(colorTarget==4)state.nightLook.background=0;}persist();closeColor();return;}
 if(settingsTab==9){if(settingsRow==5){colorRGB()=hsvRgb(picker);rememberColor(state,colorRGB());if(colorTarget==0)state.dayLook.background=0;if(colorTarget==4)state.nightLook.background=0;persist();closeColor();return;}if(settingsRow==0)picker.h=fmod(picker.h+delta*5+360,360);else if(settingsRow==1)picker.s=std::clamp(picker.s+delta*.03,0.,1.);else{int rgb=hsvRgb(picker),shift=(settingsRow-2)*8,value=(rgb>>shift)&255;value=std::clamp(value+delta*8,0,255);picker=rgbHsv((rgb&~(255<<shift))|(value<<shift));}applyPicker();return;}
 if(settingsTab==0){switch(settingsRow){case 0:state.themeMode=(state.themeMode+delta+3)%3;state.autoAppearance=state.themeMode==2;settingsScroll=0;break;case 1:state.style=(state.style+delta+3)%3;break;case 2:openColor(2);break;case 3:openColor(3);break;case 4:state.dayLook.opacity=std::clamp(state.dayLook.opacity-delta*10,0,100);break;case 5:case 6:lookEdit=state.themeMode==1||settingsRow==6;scanBackgrounds();fileFocus=backgroundGallery(editingLook().background);fileScroll=0;settingsTab=6;break;case 7:state.dayStart=(state.dayStart+delta+24)%24;break;case 8:state.nightStart=(state.nightStart+delta+24)%24;break;}persist();}
 else if(settingsTab==1){if(settingsRow==0){state.language=1-state.language;notice.clear();}if(settingsRow==1)state.time24=!state.time24;if(settingsRow==2)state.units=1-state.units;if(settingsRow==3)state.dualUnits=!state.dualUnits;if(settingsRow==4)state.hints=!state.hints;if(settingsRow==5)state.keepScreen=!state.keepScreen;if(settingsRow==7){readerText=state.networkReport.empty()?t("Обновление ещё не выполнялось","No update has run yet"):state.networkReport;if(networkLoading())readerText=t("Идёт обновление. Ниже — предыдущий результат.\n\n","Update in progress. Previous result below.\n\n")+readerText;readerScroll=0;settingsTab=13;return;}if(settingsRow==6){openColor(5);return;}persist();}
 else if(settingsTab==2){if(settingsRow==0){settingsTab=3;settingsRow=settingsScroll=0;}else if(settingsRow==1){state.followLocal=!state.followLocal;persist();updateNetwork();}else if(settingsRow==2){state.international=!state.international;persist();}else if(settingsRow==3){settingsTab=4;countryFocus=-1;countryScroll=0;}else{auto c=state.countries[settingsRow-4];openCountry(c);}}
 else if(settingsTab==3){if(settingsRow==0)updateNetwork(true);if(settingsRow==1)openCitySearch(-1);if(settingsRow==2)keyboard(3,regionName(state.location.country,state.location.region,state.language),regionLabel(state.location.country,state.language)+t(": название или код",": name or code"));if(settingsRow==3)keyboard(5,state.location.postal,postalLabel(state.location.country,state.language)+" · "+postalExample(state.location.country));}
 else if(settingsTab==4){if(countryFocus<0)keyboard(4,countrySearch,t("Поиск страны","Search countries"));else countryToggle(countryFocus);}
 else if(settingsTab==14){if(settingsRow==3){removeTrackedCity(state,cityEdit);cityEdit=-1;weatherRegion=-1;weatherDay=-1;page=3;settingsTab=2;weatherPlaceFocus=std::min(weatherPlaceFocus,(int)weatherRows().size()-1);weatherPlaceScroll=std::min(weatherPlaceScroll,weatherPlaceFocus);persist();}return;}
 else if(settingsTab==11){auto places=countryCityPlaces();if(settingsRow==(int)places.size()){openCitySearch(countryEdit);return;}cityEdit=places[settingsRow];settingsTab=12;settingsRow=settingsScroll=0;return;}else if(settingsTab==12){if(settingsRow==1)toggleCityClock();if(settingsRow==2){settingsTab=5;settingsRow=0;settingsScroll=0;}if(settingsRow==3){removeCountryCity(state,countryEdit,cityEdit);cityEdit=-1;settingsTab=11;settingsRow=settingsScroll=0;persist();}return;}
 else if(settingsTab==5&&countryEdit>=0&&countryEdit<(int)state.countries.size()){auto& c=state.countries[countryEdit];if(settingsRow==0){c.holidays=!c.holidays;persist();updateNetwork();}if(settingsRow==1){openColor(12);return;}if(settingsRow==2){settingsTab=11;settingsRow=settingsScroll=0;return;}if(settingsRow==4){openCitySearch(countryEdit);return;}if(settingsRow==5){settingsTab=10;zoneFocus=zoneScroll=0;return;}if(settingsRow==3){std::string code=c.code;state.regions.erase(std::remove_if(state.regions.begin(),state.regions.end(),[&](const WeatherPlace& p){return p.location.country==code&&(p.origin==1||p.origin==3);}),state.regions.end());state.countries.erase(state.countries.begin()+countryEdit);countryEdit=-1;settingsTab=2;settingsRow=3;settingsScroll=0;if(countryReturnPage==0){page=0;homeClockFocus=-1;}persist();updateNetwork();}}
 else if(settingsTab==6){if(fileFocus==0){openColor(lookEdit?4:0);return;}auto& a=editingLook();a.background=fileFocus<11?galleryBackground(fileFocus):5;if(fileFocus>=11)a.image=backgroundFiles[fileFocus-11];persist();settingsTab=0;settingsRow=lookEdit&&state.themeMode==2?6:5;settingsScroll=0;}
}
static void settingsBack(){if(settingsTab==14){page=3;weatherDay=-1;settingsTab=2;cityEdit=-1;return;}if(settingsTab==13){settingsTab=1;settingsRow=7;settingsScroll=2;return;}if(settingsTab==12){settingsTab=11;settingsRow=settingsScroll=0;cityEdit=-1;return;}if(settingsTab==11){settingsTab=5;settingsRow=2;settingsScroll=0;return;}if(settingsTab==10){settingsTab=5;settingsRow=5;return;}if(settingsTab==8){if(cityTarget==-2){page=3;weatherDay=-1;return;}settingsTab=cityTarget>=0?11:3;settingsRow=cityTarget>=0?0:1;settingsScroll=0;return;}if(settingsTab==9){settingsTab=7;settingsRow=0;return;}if(settingsTab==7){closeColor();return;}if(settingsTab==6){settingsTab=0;settingsRow=lookEdit&&state.themeMode==2?6:5;}else if(settingsTab==5){settingsTab=2;settingsRow=std::max(3,countryEdit+4);if(countryReturnPage==0)page=0;}else if(settingsTab==3||settingsTab==4){settingsRow=settingsTab==3?0:3;settingsTab=2;}else page=0;settingsScroll=0;}
static void changeMonth(int delta){calendarReader=false;int year=selected.y;selected=month(selected,delta);deleteConfirm=false;holidayScroll=0;if(year!=selected.y)updateNetwork();}

struct HomeTarget{int id,x,y;};
static std::vector<HomeTarget> homeTargets(){std::vector<HomeTarget> out={{0,280,194},{300,755,108}};auto clocks=trackedClocks();for(int i=clockScroll;i<(int)clocks.size()&&i<clockScroll+8;++i){int slot=i-clockScroll;out.push_back({i+1,110+slot%4*129,293+slot/4*51});}if(clocks.size()>8){if(clockScroll>0)out.push_back({80,488,393});if(clockScroll+8<(int)clocks.size())out.push_back({81,560,393});}int start=weekday({selected.y,selected.m,1});for(int d=1;d<=days(selected.y,selected.m);++d){int i=start+d-1;out.push_back({100+d,636+i%7*43,165+i/7*31});}for(int i=0;i<10;++i)out.push_back({200+i,63+i*93,458});return out;}
static void changeClockPage(int delta,int slot=0){auto count=(int)trackedClocks().size();if(count<=8)return;clockScroll=std::clamp(clockScroll+delta*8,0,(count-1)/8*8);homeFocus=std::min(count,clockScroll+slot+1);}
static void moveHome(unsigned b){if(homeBlock>=0&&b&(SCE_CTRL_LEFT|SCE_CTRL_RIGHT|SCE_CTRL_UP|SCE_CTRL_DOWN)){homeFocus=homeBlock==0?(trackedClocks().empty()?0:clockScroll+1):homeBlock==1?101:200;if(homeBlock==1)selected.d=1;homeBlock=-1;return;}if(homeFocus>=1&&homeFocus<=16){int slot=homeFocus-1-clockScroll,count=trackedClocks().size();if((b&SCE_CTRL_RIGHT)&&slot%4==3&&clockScroll+8<count){changeClockPage(1,slot/4*4);return;}if((b&SCE_CTRL_LEFT)&&slot%4==0&&clockScroll>0){changeClockPage(-1,slot/4*4+3);return;}}auto targets=homeTargets();auto current=std::find_if(targets.begin(),targets.end(),[&](const HomeTarget& t){return t.id==homeFocus;});if(current==targets.end()){homeFocus=200;return;}int dx=b&SCE_CTRL_LEFT?-1:b&SCE_CTRL_RIGHT?1:0,dy=b&SCE_CTRL_UP?-1:b&SCE_CTRL_DOWN?1:0;if(!dx&&!dy)return;double best=1e9;int chosen=homeFocus;for(const auto& t:targets){int x=t.x-current->x,y=t.y-current->y,along=dx?x*dx:y*dy,across=dx?abs(y):abs(x);if(along<=0)continue;double score=along+across*2.5;if(score<best){best=score;chosen=t.id;}}if(chosen==80||chosen==81){changeClockPage(chosen==80?-1:1);return;}homeFocus=chosen;if(homeFocus>=101&&homeFocus<=131)selected.d=homeFocus-100;}
static void openMonthPicker(){wheelMonth=selected.m;wheelYear=selected.y;wheelColumn=0;monthPicker=true;}
static void applyMonthPicker(){int old=selected.y;selected={wheelYear,wheelMonth,std::min(selected.d,days(wheelYear,wheelMonth))};monthPicker=false;if(old!=selected.y)updateNetwork();}
static void drawMonthPicker(){rect(0,65,960,479,RGBA8(0,0,0,170));rect(200,103,560,374,p.card);text(240,144,23,t("Месяц и год","Month and year"));rect(222,267,516,45,p.line);for(int i=-2;i<=2;++i){int m=(wheelMonth-1+i+12)%12+1,y=wheelYear+i,base=296+i*48;fit(235,base,i==0?24:18,monthName(m),275,i==0&&wheelColumn==0?p.accent:p.muted);text(566,base,i==0?24:18,std::to_string(y),i==0&&wheelColumn==1?p.accent:p.muted);}button(240,421,480,t("Применить","Apply"));}
static void changeWheel(int delta){if(wheelColumn==0)wheelMonth=(wheelMonth-1+delta+12)%12+1;else wheelYear=std::clamp(wheelYear+delta,1900,2099);}
static void changeTab(int delta){calendarReader=false;int ids[]={0,1,3,2},index=0;while(index<4&&ids[index]!=page)++index;page=ids[(index+delta+4)%4];if(page==2)selectSettingsSection(settingsSection());weatherDay=-1;eventEditor=false;monthPicker=false;notice.clear();}
static void controls(unsigned b){
 if(imeKind||closing)return;if(page==1&&calendarReader){if(b&SCE_CTRL_CIRCLE||b&SCE_CTRL_CROSS){calendarReader=false;return;}if(b&(SCE_CTRL_UP|SCE_CTRL_LEFT))scrollCalendarText(-1);if(b&(SCE_CTRL_DOWN|SCE_CTRL_RIGHT))scrollCalendarText(1);if(b&SCE_CTRL_LTRIGGER)changeTab(-1);if(b&SCE_CTRL_RTRIGGER)changeTab(1);return;}if(b&SCE_CTRL_LTRIGGER){changeTab(-1);return;}if(b&SCE_CTRL_RTRIGGER){changeTab(1);return;}if(monthPicker){if(b&SCE_CTRL_LEFT)wheelColumn=0;if(b&SCE_CTRL_RIGHT)wheelColumn=1;if(b&SCE_CTRL_UP)changeWheel(-1);if(b&SCE_CTRL_DOWN)changeWheel(1);if(b&SCE_CTRL_CROSS)applyMonthPicker();if(b&SCE_CTRL_CIRCLE)monthPicker=false;return;}if(b&SCE_CTRL_START){state.style=(state.style+1)%3;persist();return;}if(b&SCE_CTRL_SELECT){page=0;weatherDay=-1;eventEditor=false;if(homeBlock<0)homeBlock=homeFocus<100?1:homeFocus<200||homeFocus==300?2:0;else homeBlock=(homeBlock+1)%3;return;}
 if((page==0||page==3)&&weatherDay>=0){auto hours=hoursForDay(weatherDay);if(b&SCE_CTRL_CIRCLE){weatherDay=-1;return;}if(b&SCE_CTRL_SQUARE)openWeather(std::max(0,weatherDay-1));if(b&SCE_CTRL_TRIANGLE)openWeather(std::min((int)viewWeather().dates.size()-1,weatherDay+1));if(b&SCE_CTRL_LEFT)graphMetric=(graphMetric+5)%6;if(b&SCE_CTRL_RIGHT)graphMetric=(graphMetric+1)%6;if(b&SCE_CTRL_UP)graphHour=std::max(0,graphHour-1);if(b&SCE_CTRL_DOWN)graphHour=std::min(std::max(0,(int)hours.size()-1),graphHour+1);return;}
 if(page==3){if(b&SCE_CTRL_UP)weatherPlaceFocus=std::max(0,weatherPlaceFocus-1);if(b&SCE_CTRL_DOWN)weatherPlaceFocus=std::min((int)weatherRows().size(),weatherPlaceFocus+1);if(b&SCE_CTRL_RIGHT){manageWeatherCity();return;}if(b&SCE_CTRL_CROSS)chooseWeatherPlace();if(b&SCE_CTRL_TRIANGLE)openCitySearch(-2);if(b&SCE_CTRL_SQUARE)updateNetwork();if(b&SCE_CTRL_CIRCLE)page=0;return;}
 if(page==1&&eventEditor){if(b&SCE_CTRL_TRIANGLE){readSelectedText();return;}if(b&SCE_CTRL_CIRCLE){eventEditor=false;return;}if(b&SCE_CTRL_UP)moveEvent(-1);if(b&SCE_CTRL_DOWN)moveEvent(1);if(b&SCE_CTRL_CROSS)eventAction();if(b&(SCE_CTRL_LEFT|SCE_CTRL_RIGHT)){if(calendarAction==1)color();if(calendarAction==2)repeat();}return;}
 if(page==0){if(homeBlock>=0&&b&SCE_CTRL_CROSS){moveHome(SCE_CTRL_DOWN);return;}moveHome(b);if(b&SCE_CTRL_SQUARE)updateNetwork();if(b&SCE_CTRL_CROSS){if(homeFocus==300)openMonthPicker();else if(homeFocus>=101&&homeFocus<=131){selected.d=homeFocus-100;page=1;eventEditor=false;calendarAction=-1;homeBlock=-1;holidayScroll=0;}else if(homeFocus>=200&&homeFocus<210){weatherRegion=-1;openWeather(homeFocus-200);}else if(homeFocus==80||homeFocus==81){clockScroll=std::clamp(clockScroll+(homeFocus==80?-8:8),0,((int)trackedClocks().size()-1)/8*8);homeFocus=clockScroll+1;}else if(homeFocus>=1&&homeFocus<=16){auto clocks=trackedClocks();if(homeFocus<=(int)clocks.size())openClockCity(clocks[homeFocus-1]);}else{state.style=(state.style+1)%3;persist();}}return;}
    if(page==1){if(b&SCE_CTRL_TRIANGLE){readSelectedText();return;}if(b&SCE_CTRL_SQUARE){auto hs=holidayItems(state,selected);holidayScroll=hs.size()>3?(holidayScroll+3)%(int)hs.size():0;return;}Date before=selected;if(b&SCE_CTRL_LEFT)selected=shift(selected,-1);if(b&SCE_CTRL_RIGHT)selected=shift(selected,1);if(b&SCE_CTRL_UP)selected=shift(selected,-7);if(b&SCE_CTRL_DOWN)selected=shift(selected,7);if(key(before)!=key(selected)){calendarAction=-1;deleteConfirm=false;holidayScroll=0;if(before.y!=selected.y)updateNetwork();}if(b&SCE_CTRL_CROSS){eventEditor=true;calendarAction=0;}if(b&SCE_CTRL_CIRCLE)page=0;return;}

 if(b&SCE_CTRL_CIRCLE){settingsBack();return;}
 if(settingsTab==13){if(b&SCE_CTRL_UP)scrollCalendarText(-1);if(b&SCE_CTRL_DOWN)scrollCalendarText(1);if(b&SCE_CTRL_LEFT)scrollCalendarText(-8);if(b&SCE_CTRL_RIGHT)scrollCalendarText(8);if(b&SCE_CTRL_CROSS)settingsBack();return;}
 if(settingsTab==10){auto zones=zonesFor(state.countries[countryEdit].code);if(b&SCE_CTRL_UP)zoneFocus=std::max(0,zoneFocus-1);if(b&SCE_CTRL_DOWN)zoneFocus=std::min((int)zones.size()-1,zoneFocus+1);if(b&SCE_CTRL_CROSS&&!zones.empty()){cityTarget=countryEdit;cityResults=Json::array();citySearch=zoneCity(zones[zoneFocus]);cityFocus=-1;cityScroll=0;settingsTab=8;settingsRow=0;keyboard(2,citySearch,t("Поиск города","Search cities"));}return;}
 if(settingsTab==8){if(b&SCE_CTRL_UP)cityFocus=std::max(-1,cityFocus-1);if(b&SCE_CTRL_DOWN)cityFocus=std::min((int)cityResults.size()-1,cityFocus+1);if(b&SCE_CTRL_CROSS){if(cityFocus<0)keyboard(2,citySearch,t("Поиск города","Search cities"));else chooseCity(cityFocus);}if(b&SCE_CTRL_TRIANGLE)keyboard(2,citySearch,t("Поиск города","Search cities"));return;}
 if(settingsTab==4){auto c=filteredCountries();if(b&SCE_CTRL_UP)countryFocus=std::max(-1,countryFocus-1);if(b&SCE_CTRL_DOWN)countryFocus=std::min((int)c.size()-1,countryFocus+1);if(b&SCE_CTRL_LEFT)countryFocus=std::max(-1,countryFocus-6);if(b&SCE_CTRL_RIGHT)countryFocus=std::min((int)c.size()-1,countryFocus+6);if(b&SCE_CTRL_TRIANGLE)keyboard(4,countrySearch,t("Поиск страны","Search countries"));if(b&SCE_CTRL_SQUARE){countrySearch.clear();countryFocus=-1;countryScroll=0;}if(b&SCE_CTRL_CROSS)settingsAction();return;}
 if(settingsTab==6){if(b&SCE_CTRL_LEFT)fileFocus=std::max(0,fileFocus-1);if(b&SCE_CTRL_RIGHT)fileFocus=std::min(settingCount()-1,fileFocus+1);if(b&SCE_CTRL_UP)fileFocus=std::max(0,fileFocus-3);if(b&SCE_CTRL_DOWN)fileFocus=std::min(settingCount()-1,fileFocus+3);if(b&SCE_CTRL_SQUARE)scanBackgrounds();if(b&SCE_CTRL_CROSS)settingsAction();return;}
 if(settingsTab==9){if(b&SCE_CTRL_CIRCLE){settingsBack();return;}if(settingsRow==1){if(b&SCE_CTRL_LEFT)picker.s=std::max(0.,picker.s-.03);if(b&SCE_CTRL_RIGHT)picker.s=std::min(1.,picker.s+.03);if(b&SCE_CTRL_UP)picker.v=std::min(1.,picker.v+.03);if(b&SCE_CTRL_DOWN)picker.v=std::max(0.,picker.v-.03);applyPicker();}else{if(b&SCE_CTRL_LEFT)settingsAction(-1);if(b&SCE_CTRL_RIGHT)settingsAction();if(b&SCE_CTRL_UP)settingsRow=std::max(0,settingsRow-1);if(b&SCE_CTRL_DOWN)settingsRow=std::min(5,settingsRow+1);}if(b&SCE_CTRL_CROSS)settingsAction();return;}
 if(settingsTab==7){int count=settingCount();if(b&SCE_CTRL_LEFT)paletteFocus=std::max(0,paletteFocus-1);if(b&SCE_CTRL_RIGHT)paletteFocus=std::min(count-1,paletteFocus+1);if(b&SCE_CTRL_UP)paletteFocus=std::max(0,paletteFocus-(colorTarget>=10?6:12));if(b&SCE_CTRL_DOWN)paletteFocus=std::min(count-1,paletteFocus+(colorTarget>=10?6:12));if(b&SCE_CTRL_TRIANGLE&&colorTarget<10){paletteFocus=73+state.recentColors.size();settingsAction();}else if(b&SCE_CTRL_CROSS)settingsAction();return;}
 
 if(b&SCE_CTRL_UP)settingsRow=std::max(0,settingsRow-1);if(b&SCE_CTRL_DOWN)settingsRow=std::min(settingCount()-1,settingsRow+1);if(b&SCE_CTRL_CROSS)settingsAction(settingsTab==5&&settingsRow==2?0:1);bool adjustable=settingsTab==1||settingsTab==9||(settingsTab==0&&(settingsRow==0||settingsRow==1||settingsRow==4||settingsRow==7||settingsRow==8))||(settingsTab==5&&settingsRow==0)||(settingsTab==12&&settingsRow==1);if(adjustable&&b&SCE_CTRL_LEFT)settingsAction(-1);if(adjustable&&b&SCE_CTRL_RIGHT)settingsAction();if(b&SCE_CTRL_TRIANGLE&&settingsTab==2&&(settingsRow==1||settingsRow==2))openColor(settingsRow==1?10:11);
}
// Each stick has its own repeat state and role; d-pad preserves direct navigation.
static void stickControls(unsigned b,bool right){if(!b||imeKind||closing)return;if(page==1&&calendarReader){controls(b);return;}if(monthPicker){controls(b);return;}if(!right){controls(b);return;}if((page==0||page==3)&&weatherDay>=0){auto h=hoursForDay(weatherDay);if(b&(SCE_CTRL_LEFT|SCE_CTRL_UP))graphHour=std::max(0,graphHour-1);if(b&(SCE_CTRL_RIGHT|SCE_CTRL_DOWN))graphHour=std::min(std::max(0,(int)h.size()-1),graphHour+1);return;}if(page==0||page==1){if(b&SCE_CTRL_RIGHT)changeMonth(1);if(b&SCE_CTRL_LEFT)changeMonth(-1);if(homeFocus>=101&&homeFocus<=131)homeFocus=100+selected.d;return;}if(page==1){if(!eventEditor){eventEditor=true;calendarAction=0;}if(b&SCE_CTRL_UP)calendarAction=std::max(0,calendarAction-1);if(b&SCE_CTRL_DOWN)calendarAction=std::min(3,calendarAction+1);if(b&(SCE_CTRL_LEFT|SCE_CTRL_RIGHT)){if(calendarAction==1)color();if(calendarAction==2)repeat();}return;}if(page==2){if(settingsTab==9){if(b&SCE_CTRL_UP)settingsRow=std::max(0,settingsRow-1);if(b&SCE_CTRL_DOWN)settingsRow=std::min(5,settingsRow+1);if(b&SCE_CTRL_LEFT)settingsAction(-1);if(b&SCE_CTRL_RIGHT)settingsAction();return;}int delta=b&(SCE_CTRL_UP|SCE_CTRL_LEFT)?-1:1;selectSettingsSection((settingsSection()+delta+3)%3);return;}controls(b);}
static void scrollGesture(int steps){if(imeKind||closing)return;if((page==1&&calendarReader)||(page==2&&settingsTab==13)){scrollCalendarText(steps);return;}if(monthPicker){changeWheel(steps);return;}if(page==2&&settingsTab==4){auto c=filteredCountries();countryFocus=std::clamp(countryFocus+steps,-1,std::max(-1,(int)c.size()-1));}else if(page==2&&settingsTab==8)cityFocus=std::clamp(cityFocus+steps,-1,std::max(-1,(int)cityResults.size()-1));else if(page==2&&settingsTab==6)fileFocus=std::clamp(fileFocus+steps*3,0,settingCount()-1);else if(page==2&&settingsTab==7)paletteFocus=std::clamp(paletteFocus+steps*6,0,settingCount()-1);else if(page==2)settingsRow=std::clamp(settingsRow+steps,0,std::max(0,settingCount()-1));else if((page==0||page==3)&&weatherDay>=0){auto hours=hoursForDay(weatherDay);graphHour=std::clamp(graphHour+steps,0,std::max(0,(int)hours.size()-1));}}
static void touch(int x,int y){if(page==1&&calendarReader){if(x>=864&&y>=82&&y<132)calendarReader=false;return;}
 if(imeKind||closing)return;if(monthPicker){if(y>=421&&y<=463){applyMonthPicker();return;}if(x>=222&&x<=738&&y>=172&&y<=408){wheelColumn=x<520?0:1;int delta=(int)std::round((y-296)/48.f);changeWheel(delta);}else monthPicker=false;return;}if(y>=13&&y<=55){if(x>=350&&x<498)page=0;else if(x>=498&&x<646)page=1;else if(x>=646&&x<794)page=3;else if(x>=794){page=2;selectSettingsSection(settingsSection());}weatherDay=-1;eventEditor=false;notice.clear();return;}
 if((page==0||page==3)&&weatherDay>=0){if(y>=68&&y<=115&&x>=426&&x<936){openWeather((x-426)/51);return;}if(y>=120&&y<=162){graphMetric=std::clamp((x-20)/155,0,5);return;}if(x>=136&&x<=607&&y>=174&&y<=395){auto h=hoursForDay(weatherDay);graphHour=std::clamp((int)std::round((x-136)/471.f*std::max(0,(int)h.size()-1)),0,std::max(0,(int)h.size()-1));}return;}
 if(page==0){if(trackedClocks().size()>8&&y>=378&&y<407&&x>=476&&x<578){if(x<502)clockScroll=std::max(0,clockScroll-8);if(x>=548)clockScroll=std::min(((int)trackedClocks().size()-1)/8*8,clockScroll+8);homeFocus=clockScroll+1;return;}if(x>=598&&x<=932&&y>=82&&y<126){openMonthPicker();return;}auto clocks=trackedClocks();if(x>=48&&x<564&&y>=270&&y<372&&!clocks.empty()){int i=clockScroll+(y-270)/51*4+(x-48)/129;if(i<(int)clocks.size())openClockCity(clocks[i]);return;}if(y>=409&&y<=518&&x>=20&&x<950){openWeather(std::min(9,(x-20)/93));return;}if(x>=617&&x<918&&y>=151&&y<337){int day=(y-151)/31*7+(x-617)/43-weekday({selected.y,selected.m,1})+1;if(day>=1&&day<=days(selected.y,selected.m)){selected.d=day;page=1;eventEditor=false;calendarAction=-1;homeBlock=-1;holidayScroll=0;}return;}if(x>=898&&y>=88&&y<125)changeMonth(1);return;}
 if(page==3){if(y>=92&&y<500){weatherPlaceFocus=weatherPlaceScroll+(y-92)/68;if(weatherPlaceFocus<=(int)weatherRows().size()){if(x>=585&&x<628)manageWeatherCity();else chooseWeatherPlace();}}return;}
 if(page==1&&eventEditor){auto rows=eventRows();int row=(y-134)/83;if(y>=134&&row<(int)rows.size()&&(y-134)%83<70){calendarAction=rows[row];eventAction();}return;}
 if(page==1){if(x>=28&&x<=664&&y>=82&&y<136){openMonthPicker();return;}if(x>=49&&x<651&&y>=173&&y<467){int day=(y-173)/49*7+(x-49)/86-weekday({selected.y,selected.m,1})+1;if(day>=1&&day<=days(selected.y,selected.m)){selected.d=day;eventEditor=true;calendarAction=0;deleteConfirm=false;holidayScroll=0;}return;}if(x>=684&&y>=446&&y<480){auto marks=marksFor(state,selected);if(!marks.empty()&&!marks[0].second.title.empty())repeat();return;}if(x>=684&&y>=226&&y<410){auto hs=holidayItems(state,selected);int row=(y-226)/54+holidayScroll;if(row<(int)hs.size())openCalendarText(holidayTitle(hs[row]));return;}if(x>=684&&y>=82&&y<226){auto marks=marksFor(state,selected);if(!marks.empty()&&!marks.front().second.title.empty())openCalendarText(marks.front().second.title);else{eventEditor=true;calendarAction=0;}}return;}
 if(settingsTab==13){if(x>=860&&y>=82&&y<136)settingsBack();return;}
 if(y>=78&&y<=120&&x>=20){selectSettingsSection(std::min(2,(x-20)/310));return;}
 if(settingsTab==13){if(x>=860&&y>=82&&y<136)settingsBack();return;}
 if(settingsTab==10){if(y>=132&&y<504){auto z=zonesFor(state.countries[countryEdit].code);zoneFocus=zoneScroll+(y-132)/62;if(zoneFocus<(int)z.size())controls(SCE_CTRL_CROSS);}return;}
 if(settingsTab==8){if(y>=132&&y<=174)keyboard(2,citySearch,t("Поиск города","Search cities"));else if(y>=187&&y<497)chooseCity(cityScroll+(y-187)/62);return;}
 if(settingsTab==7){if(colorTarget>=10){if(y>=140&&y<294&&x>=44){int i=(y-140)/77*6+(x-44)/147;if(i<10){paletteFocus=i;settingsAction();}}return;}int recent=state.recentColors.size();if(y>=153&&y<185){if(x>=44&&x<88){paletteFocus=0;settingsAction();}else if(x>=170){int i=(x-170)/60;if(i<recent&&(x-170)%60<44){paletteFocus=i+1;settingsAction();}}}else if(y>=202&&y<460&&x>=44&&x<920){int i=(y-202)/43*12+(x-44)/73;if(i<72&&(x-44)%73<35&&(y-202)%43<35){paletteFocus=recent+1+i;settingsAction();}}else if(y>=466&&y<=508){paletteFocus=recent+73;settingsAction();}return;}
 if(settingsTab==9){if(x>=44&&x<=344&&y>=142&&y<=442){settingsRow=1;picker.s=(x-44)/300.;picker.v=1-(y-142)/300.;applyPicker();}else if(x>=360&&x<=392&&y>=142&&y<=442){settingsRow=0;picker.h=std::min(359.,(y-142)*360./300);applyPicker();}else if(x>=458&&y>=151&&y<400){int channel=std::clamp((y-151)/87,0,2);settingsRow=channel+2;int value=std::clamp((x-476)*255/408,0,255);int rgb=hsvRgb(picker);picker=rgbHsv((rgb&~(255<<(channel*8)))|(value<<(channel*8)));}else if(x>=458&&y>=425&&y<=467){settingsRow=5;settingsAction();}return;}
 if(settingsTab==4){if(y>=132&&y<=174){countryFocus=-1;settingsAction();}else if(y>=182&&y<506){countryFocus=countryScroll+(y-182)/54;countryToggle(countryFocus);}return;}
 if(settingsTab==6){if(x>=32&&x<953&&y>=136&&y<510){int col=(x-32)/307,row=(y-136)/187;if(col<3&&row<2&&(x-32)%307<288&&(y-136)%187<176){fileFocus=fileScroll+row*3+col;if(fileFocus<settingCount())settingsAction();}}return;}
 if(y>=132&&y<504){settingsRow=settingsScroll+(y-132)/62;if(settingsRow<settingCount()){if(settingsTab==2&&(settingsRow==1||settingsRow==2)&&x>=835)openColor(settingsRow==1?10:11);else settingsAction(settingsTab==5&&settingsRow==2?0:1);}}
}
static std::string footerHint(){if(page==2&&settingsTab==13)return t("Левый стик / стрелки / свайп: отчёт · X/O: закрыть","Left stick / arrows / swipe: report · X/O: close");if(page==1&&calendarReader)return t("Стики / стрелки / свайп: текст · X/O: закрыть","Sticks / arrows / swipe: text · X/O: close");if(monthPicker)return t("Стрелки: месяц / год · подтверждение: применить","Arrows: month / year · confirm: apply");std::string enter=circleEnter?"O":"X",back=circleEnter?"X":"O";if(page==3&&weatherDay<0)return t("Вправо: управление городом · Triangle: поиск · Square: обновить","Right: manage city · Triangle: search · Square: refresh");if((page==0||page==3)&&weatherDay>=0)return t("Стрелки: график / час · Square/Triangle: день · ","Arrows: chart / hour · Square/Triangle: day · ")+back+t(": назад",": back");if(page==0)return enter+t(": прогноз · L/R: вкладки · Start: часы · Select: блок",": forecast · L/R: tabs · Start: clock · Select: block");if(page==1)return enter+t(": настройки дня · Triangle: весь текст · стрелки: день · правый стик: месяц",": day settings · Triangle: full text · arrows: day · right stick: month");if(page==2&&settingsTab==9)return t("Левый стик: цветовое поле · правый: оттенок · стрелки: RGB / применить · ","Left stick: color field · right: hue · arrows: RGB / apply · ")+back+t(": отмена",": cancel");if(settingsTab==4)return enter+t(": выбрать · Triangle: поиск · Square: очистить · ",": select · Triangle: search · Square: clear · ")+back+t(": назад",": back");return enter+t(": изменить · стрелки: выбор · правый стик: раздел · ",": change · arrows: select · right stick: section · ")+back+t(": назад",": back");}
static std::string displayNotice(){if(!state.language)return notice;static const std::map<std::string,std::string> messages={{"Не удалось сохранить: проверь место на карте","Save failed: check storage space"},{"Сеть недоступна. Календарь работает офлайн","Network unavailable. Calendar works offline"},{"Загрузка места, погоды и праздников…","Loading location, weather and holidays…"},{"Закрытие…","Closing…"},{"Ещё раз Triangle — удалить свою отметку","Confirm deletion again"},{"Отметка удалена","Mark removed"},{"Не удалось открыть клавиатуру","Could not open keyboard"},{"PNG/JPEG: максимум 2048 × 2048","PNG/JPEG: maximum 2048 × 2048"},{"Не удалось открыть изображение","Could not load image"}};auto it=messages.find(notice);return it==messages.end()?notice:it->second;}
